import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_WIDTH, SCREEN_HEIGHT} from '../../../../lib/utils/constants';

export default styles = StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerTextStyle: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
  },
  datingStyle: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginLeft: '5%',
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
  },
  headingStyle: {
    color: 'white',
    fontSize: 12,
  },
  container: {
    flex: 1,
    paddingTop: '5%',
  },
  cardContainer: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
    padding: '5%',
    borderRadius: 10,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  avatarContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowStyle: {
    marginTop: '5%',
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    // alignItems: 'center',
  },
  rowContainer: {
    marginTop: '5%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowContainer1: {
    marginVertical: '5%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewStyle: {
    flex: 0.33,
    height: 40,
    marginHorizontal: 3,
    backgroundColor: '#E9E9E9',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleText: {
    marginVertical: '5%',
    fontSize: 22,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  titleText1: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  gap: {
    width: 15,
  },
  designationText: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  headingText: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#38474F',
  },
  colorHeadingText: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_EDUCATION,
  },
  colorHeadingText1: {
    fontSize: 18,
    fontFamily: themeStyle.FONT_MEDIUM,
    color: '#99CC66',
  },
  colorText: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#99CC66',
  },
  descText: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
  },
  btnContainer: {
    flex: 0.3,
    elevation: 5,
    justifyContent: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '5%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  btonContainer: {
    marginVertical: '2.5%',
    backgroundColor: '#99CC66',
    height: 50,
    flexDirection: 'row',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  whiteText: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: 'white',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
    backgroundColor: 'lightgray',
    paddingVertical: '2.5%',
  },
  btnText: {
    color: 'white',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  modalContainer: {
    zIndex: 1,
    elevation: 7,
    position: 'absolute',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    height: SCREEN_HEIGHT,
    width: SCREEN_WIDTH,
    flex:1,
    flexDirection:"column",
    // paddingTop: SCREEN_HEIGHT * 0.225,
    // justifyContent:"flex-end",
  },
  grayText: {
    color: '#959FAE',
    textAlign: 'center',
    fontSize: 10,
    paddingVertical: '5%',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  sliderStyle: {
    width: SCREEN_WIDTH,
    height: 60,
    marginTop: '5%',
    bottom: 20,
  },
  linkText: {
    color: '#0ABDE3',
    textAlign: 'center',
    fontSize: 10,
    paddingVertical: '5%',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  textContainer: {
    justifyContent: 'flex-start',
    marginTop: '5%',
    marginBottom: '15%',
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerStyle: {
    height: 110,
    marginBottom: 0,
    borderRadius: 10,
    // width: SCREEN_WIDTH * 0.9,
    borderColor: themeStyle.COLOR_EDUCATION,
    borderWidth: 2,
    // width:SCREEN_WIDTH*0.9
  },
  inputContainerStyle: {
    borderBottomWidth: 0,
    backgroundColor: '#FFFF',
    borderRadius: 5,
    height: 100,
    width: "100%",
    // alignSelf: 'center',
  },
  inputStyle: {
    height: 90,
    textAlignVertical: 'top',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2.5%',
  },
  inputStyle1: {
    fontSize: 14,
    marginLeft: '5%',
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  inputConttainer1: {
    marginTop: '2.5%',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    justifyContent: 'center',
    width: SCREEN_WIDTH * 0.425,
    height: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    borderColor: themeStyle.COLOR_EDUCATION,
    borderWidth: 2,
    elevation: 1,
  },
  desc: {
    // marginTop: '5%',
    marginLeft: '1%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  inputConttainer: {
    marginTop: '2.5%',
    // backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
});
