import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    flex: 0.95,
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  heading: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 20,
    color: themeStyle.COLOR_BLACK,
  },
  headingContainer: {
    marginTop: '5%',
    marginHorizontal: '5%',
  },
  linkContainer: {
    borderWidth: 2,
    borderColor: '#BBD7EC',
    height: 36,
    borderRadius: 7,
    position: 'absolute',
    bottom: 5,
    alignSelf: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  linkInput: {
    height: 36,
    fontSize: 14,
    color: themeStyle.INPUT_TEXT,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'center',
    width: '90%',
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  containerStyle: {
    height: 110,
    marginBottom: 0,
    width: '100%',
    color: themeStyle.INPUT_TEXT,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingHorizontal: 10,
  },
  inputContainerStyle: {
    borderWidth: 2,
    borderBottomWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#FFFF',
    borderRadius: 8,
    height: 230,
    padding: 5,
  },
  inputStyle: {
    height: 110,
    textAlignVertical: 'top',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2.5%',
    paddingTop: 10,
    borderBottomWidth: 0,
  },
  box: {
    height: 19,
    width: 22,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 22,
    borderRadius: 3,
    backgroundColor: themeStyle.CYAN_BLUE,
  },
  rowContainer: {
    flexDirection: 'row',
  },
  row: {
    flex: 0.37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  margin: {
    marginLeft: '5%',
    marginTop: 12,
  },
  option: {
    marginLeft: 8,
    fontSize: 16,
    color: themeStyle.INPUT_TEXT,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 8,
    fontSize: 16,
    color: themeStyle.INPUT_TEXT,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginBottom: 8,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  buttonContainer: {
    marginTop: '5%',
    marginHorizontal: '5%',
  },
  addMediaStyle: {
    flexDirection: 'row',
    marginTop: '5%',
    padding: '5%',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'lightgray',
  },
  btnContainer: {
    justifyContent: 'flex-end',
    marginTop: '5%',
    marginHorizontal: '5%',
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectFriends: {
    color: themeStyle.INPUT_TEXT,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  darkDash: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    width: 58,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 58,
    height: 5,
    borderRadius: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFF',
    borderRadius: 10,
    paddingHorizontal: '2.5%',
    height: 50,
    borderWidth: 2,
    // borderBottomWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
  },
  inputStyle1: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2.5%',
  },
  inputConttainer1: {
    marginTop: '1%',
    height: 50,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
  },
  imageStyle: {
    width: SCREEN_WIDTH,
    height: 350,
  },
});
