import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';
import {scaleFont, scaleImage} from '../../../../lib/utils/global';

export default StyleSheet.create({
  buttonStyleDone: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeStyle.COLOR_EXERCISE_BUTTON,
    height: 45,
    marginBottom: SCREEN_HEIGHT * 0.05,
    width: SCREEN_WIDTH * 0.5,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: themeStyle.COLOR_EXERCISE_BUTTON,
  },
  headerDay: {
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 10,
    marginLeft: 20,
  },
  headerDayText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headerTitleText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerBtn: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: themeStyle.BAR_COLOR,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  btnText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: scaleFont(12),
    marginLeft: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {
    flex: 1,
    paddingTop: '5%',
  },
  contentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH,
    paddingLeft: '1%',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '2.5%',
    marginVertical: '2.5%',
    marginBottom: '5%',
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#38474F',
    paddingVertical: '2.5%',
    paddingHorizontal: '14%',
    borderRadius: 10,
  },
  playButtonContainer: {
    backgroundColor: themeStyle.WHITE_SMOKE,
    width: 70,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playText: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: scaleFont(12),
    color: themeStyle.COLOR_BLACK_LIGHT,
    marginTop: 8,
  },
  headerContainer: {
    paddingTop: '5%',
    paddingBottom: '25%',
    backgroundColor: 'white',
    height: SCREEN_HEIGHT,
  },
  day: {
    fontSize: scaleFont(32),
    color: themeStyle.PURPLE_COLOR,
    paddingHorizontal: '2%',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  fontBold: {
    fontFamily: themeStyle.FONT_BOLD,
  },
  flatlistContentContainer: {
    paddingBottom: '20%',
    alignItems: 'center',
  },
  image: {
    width: SCREEN_HEIGHT * 0.15,
    height: SCREEN_HEIGHT * 0.15,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    resizeMode: 'contain',
  },
  imageContainer: {flex: 0.5, alignItems: 'flex-start'},
  restDayContainer: {
    padding: '4%',
    marginTop: '2%',
    flex: 1,
  },
  restDayText: {
    color: themeStyle.PURPLE_COLOR,
    fontSize: scaleFont(30),
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2%',
    marginTop: '1%',
  },
  center: {
    textAlign: 'center',
  },
  cheatDay: {
    textAlign: 'center',
    color: themeStyle.PURPLE_COLOR,
    marginVertical: '2%',
    fontSize: scaleFont(20),
    fontFamily: themeStyle.FONT_REGULAR,
  },
  restGif: {
    width: scaleImage(SCREEN_WIDTH * 0.75),
    height: scaleImage(SCREEN_WIDTH * 0.75),
    borderRadius: 10,
    marginVertical: '6%',
    alignSelf: 'center',
  },
  textStyleMenu: {
    color: themeStyle.COLOR_WHITE,
    fontSize: scaleFont(16),
    fontFamily: themeStyle.FONT_REGULAR,
  },
  exerciseCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 5,
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    backgroundColor: themeStyle.COLOR_WHITE,
    width: SCREEN_WIDTH * 0.9,
    borderRadius: 10,
    marginHorizontal: SCREEN_WIDTH * 0.02,
    marginTop: '5%',
    height: 130,
  },
  exerciseInfo: {
    padding: '5%',
    flex: 0.5,
    backgroundColor: themeStyle.ORANGE,
    justifyContent: 'center',
    height: '100%',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  exerciseName: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    textTransform: 'capitalize',
  },
  exerciseDuration: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.COLOR_WHITE,
  },
  scrollView: {marginHorizontal: SCREEN_WIDTH * 0.02},
  flex: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
  },
});
