import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
    paddingTop: 13,
  },
  freelancerContainer: {flex: 1, padding: 20, paddingBottom: 100},
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  heading: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 30,
    marginBottom: 5,
    marginTop: '5%',
    paddingHorizontal: 15,
  },
  headingBold: {
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.CARRER_PRIMARY,
  },
  headingText: {
    marginVertical: '2.5%',
    fontSize: 16,
    color: themeStyle.CARRER_PRIMARY,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputConttainer1: {
    marginTop: '2.5%',
    height: 60,
    paddingHorizontal: 17,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 10,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderWidth: 2,
    color: themeStyle.COLOR_BLACK,
  },
  row2: {flexDirection: 'row', justifyContent: 'space-between'},
  desc1: {
    marginHorizontal: '2.5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  country: {
    marginHorizontal: '2.5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textTransform: 'capitalize',
  },
  description: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderWidth: 2,
    borderRadius: 10,
    height: 120,
    marginTop: 8,
    paddingTop: 23,
    paddingHorizontal: 17,
  },
  showcaseButton: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themeStyle.CARRER_SECONDARY,
    borderRadius: 10,
    width: 190,
    height: 47,
    marginTop: 8,
  },
  showcase: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
  },
  optional: {
    color: themeStyle.COLOR_GREY,
    fontSize: 13,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 8,
  },
  finishBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 60,
    backgroundColor: themeStyle.CARRER_SECONDARY,
    borderRadius: 10,
    marginTop: 100,
    marginBottom: 40,
  },
  price: {
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    marginTop: 24,
    marginBottom: 8,
  },
  addSocialMediaProfileBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 60,
    borderWidth: 2,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderRadius: 10,
    marginTop: 20,
    paddingHorizontal: 17,
  },
  buttonContainer: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  buttonText: {
    textAlign: 'center',
    paddingHorizontal: 10,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
  },
  confirm: {
    height: 53,
    width: '49%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themeStyle.CARRER_SECONDARY,
    borderRadius: 10,
  },
  cancel: {
    height: 53,
    width: '49%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeStyle.CARRER_SECONDARY,
  },
  selectedLang: {
    height: 31,
    paddingHorizontal: 17,
    backgroundColor: themeStyle.CARRER_SECONDARY,
    marginRight: 8,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  minusIcon: {
    height: 20,
    width: 20,
    marginLeft: 5,
    position: 'absolute',
    right: -11,
    top: -6,
  },
  box: {
    height: 32,
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: themeStyle.CARRER_SECONDARY,
    marginRight: 8,
    marginTop: 8,
  },
  profileCreatedText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    textAlign: 'center',
    marginTop: '8%',
  },
});
