import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerTextStyle: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
  },
  datingStyle: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginLeft: '5%',
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
  },
  headingStyle: {
    color: 'white',
    fontSize: 12,
  },
  container: {
    flex: 1,
  },
  heading: {
    color: '#99CC66',
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 22,
  },
  btnContainer: {
    marginHorizontal: '10%',
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desc: {
    // marginTop: '5%',
    marginLeft: '1%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  desc1: {
    marginTop: '5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  desc2: {
    marginHorizontal: '2.5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  inputConttainer: {
    // marginTop: "2.5%",
    // backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  grayText: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  rowContainer: {
    marginTop: '2.5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  box: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 19,
    borderColor: 'white',
    borderWidth: 2,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.EDUCATION_BROWN,
  },
  rowContainer1: {
    flexDirection: 'row',
  },
  row: {
    flex: 0.37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'gray',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'lightgray',
  },
  dropDownContainerStyle: {
    backgroundColor: 'lightgray',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 100,
    height: 40,
  },

  option: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
   
    fontSize: 14,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  btnContainer: {
    flex: 0.2,
    elevation: 5,
    justifyContent: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '5%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  btnText: {
    color: 'white',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  btnText1: {
    color: 'gray',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
    backgroundColor: 'lightgray',
    paddingVertical: '2.5%',
  },
  containerStyle: {
    height: 110,
    marginBottom: 0,
    // width:SCREEN_WIDTH*0.9
  },
  inputContainerStyle: {
    borderBottomWidth: 2,
    backgroundColor: '#FFFF',
    borderRadius: 5,
    height: 100,
    borderWidth:2,
    borderColor:themeStyle.COLOR_EDUCATION,
    width: SCREEN_WIDTH * 0.9,
    alignSelf: 'center',
  },
  inputStyle: {
    height: 90,
    textAlignVertical: 'top',
    fontSize: 14,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2.5%',
  },
  inputStyle1: {
    fontSize: 14,
    marginLeft: '5%',
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  inputConttainer1: {
    marginTop: '2.5%',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    justifyContent: 'center',
    width: SCREEN_WIDTH * 0.425,
    height: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    borderColor: themeStyle.COLOR_EDUCATION,
    borderWidth: 2,
    elevation: 1,
  },
  margin: {
    marginVertical: 10,
  },
  inputConttainer2: {
    marginTop: '2.5%',
    height: 50,
    width: SCREEN_WIDTH * 0.9,
    paddingHorizontal: '2.5%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderColor: themeStyle.COLOR_EDUCATION,
    borderWidth: 2,
    borderRadius: 10,
  },
});
