import {StyleSheet} from 'react-native';
import themeStyle from '../../../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
  },
  breathe: {
    fontSize: 32,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PURPLE_COLOR,
    marginTop: 30,
    marginLeft: 20,
    marginBottom: 14,
  },
  exercise: {
    fontFamily: themeStyle.FONT_BOLD,
  },
  circleContainer: {
    width: SCREEN_WIDTH * 0.8,
    height: SCREEN_WIDTH * 0.8,
    borderRadius: 200,
    backgroundColor: themeStyle.ORANGE_LIGHT,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    marginTop: '20%',
  },
  circle: {
    width: SCREEN_WIDTH * 0.5,
    height: SCREEN_WIDTH * 0.5,
    borderRadius: 120,
    backgroundColor: themeStyle.COLOR_YELLOWISH,
    zIndex: 2,
    margin: 5,
  },
  button: {
    height: 70,
    width: 70,
    borderRadius: 5,
    backgroundColor: themeStyle.ORANGE,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
    marginBottom: 70,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
  },
  phase: {
    textAlign: 'center',
    marginTop: 17,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 20,
    color: themeStyle.COLOR_BLACK,
  },
  progressContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  progress: {
    width: 40,
    height: 8,
    borderRadius: 8,
    marginHorizontal: 2,
  },
  finishedView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  congratulations: {
    fontSize: 32,
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.PURPLE_COLOR,
    textAlign: 'center',
    marginHorizontal: 20,
  },
  workoutComplete: {
    fontSize: 22,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PURPLE_COLOR,
    marginTop: 20,
    textAlign: 'center',
    lineHeight: 30,
    marginHorizontal: 20,
  },
  timer: {
    textAlign: 'center',
    fontSize: 70,
    position: 'absolute',
    fontFamily: themeStyle.FONT_MEDIUM,
    left: 0,
    right: 0,
    zIndex: 3,
    color: themeStyle.COLOR_WHITE,
  },
  progressBar: {
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 1,
  },
});
