import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  container: {
    flex: 1,
  },
  innerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    paddingVertical: '2.5%',
  },
  rowContainer: {
    padding: '5%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowContainer1: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.BUTTON_COLOR,
    borderRadius: 10,
    width: SCREEN_WIDTH * 0.4,
    height: 40,
  },
  tabStyle: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuButton: {
    backgroundColor: 'lightgray',
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.15,
    height: 40,
    borderRadius: 10,
  },
  profileName: {
    fontSize: 22,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#38474F',
  },
  btnText: {
    color: 'white',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayTier: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textTransform: 'capitalize',
    color: '#959FAE',
  },
  grayTier1: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
    textTransform: 'capitalize',
    color: '#959FAE',
  },
  buttonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
    backgroundColor: 'lightgray',
    paddingVertical: '2.5%',
    paddingHorizontal: '5%',
  },
  descContainer: {
    paddingHorizontal: '5%',
    paddingVertical: '2.5%',
    borderBottomWidth: 0.5,
    borderColor: 'lightgray',
  },
  descText: {
    color: '#313131',
    fontSize: 12,
    marginTop: 5,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  nameText: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    textTransform: 'capitalize',
    marginBottom: 5,
  },
  hashText: {
    // fontSize: 10,
    color: themeStyle.COLOR_GREEN,
    fontFamily: themeStyle.FONT_REGULAR,
    textTransform: 'capitalize',
  },
  whiteText: {
    marginLeft: 5,
    fontSize: 10,
    color: 'white',
  },
  grayText: {
    fontSize: 14,
    color: '#2F2F2F',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blueText: {
    fontSize: 12,
    color: 'blue',
    fontFamily: themeStyle.FONT_REGULAR,
    textDecorationLine: 'underline',
  },
  blackText: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_BOLD,
  },
  imageStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    height: SCREEN_HEIGHT * 0.35,
    width: SCREEN_WIDTH,
  },
  listContainer: {
    flex: 1,
    padding: 25,
  },
  listTitle: {
    fontSize: 16,
    marginBottom: 20,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  listButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  listIcon: {
    // fontSize: 26,
    color: themeStyle.PRIMARY_TINT_COLOR,
    marginRight: 10,
    // width: 30
  },
  listLabel: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  sendComment: {
    borderWidth: 2,
    height: 45,
    width: 38,
    justifyContent: 'center',
    borderRadius: 10,
    marginRight: 2,
    marginBottom: 25,
    width: '13%',
    alignItems: 'center',
  },
  impressionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 10,
    height: 43,
    marginBottom: 15,
  },
  impressionsText: {
    fontSize: themeStyle.FONT_SIZE_MEDIUM,
    color: themeStyle.BUTTON_COLOR,
    marginLeft: 8,
  },
  commentText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    marginTop: 24,
  },
  options: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    height: 46,
    justifyContent: 'center',
  },
  pollText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  optionNumber: {
    backgroundColor: themeStyle.CYAN_BLUE,
    justifyContent: 'center',
    height: 40,
    borderRadius: 6,
    position: 'absolute',
    left: 1,
  },
  optionText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingLeft: 12,
  },
  optionTitle: {
    fontSize: 24,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
    paddingLeft: 12,
  },
  percentageContainer: {
    height: 40,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    flex: 1,
  },
  linkContainer: {
    backgroundColor: themeStyle.CYAN_BLUE,
    paddingHorizontal: 10,
    height: 55,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginTop: -10,
    justifyContent: 'center',
  },
  linkInnerContainer: {
    borderWidth: 1,
    borderColor: themeStyle.COLOR_WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 10,
    height: 36,
    borderRadius: 8,
  },
  linkText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  pollContainer: {
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 16,
    borderWidth: 10,
    borderColor: themeStyle.CYAN_BLUE,
    marginTop: 10,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
  },
});
