import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';

export default StyleSheet.create({
  container: {
    flex: 0.9,
  },
  heading: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 30,
    marginBottom: 5,
    marginTop: '5%',
  },
  btnContainer: {
    marginHorizontal: '5%',
    marginVertical: '10%',
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  desc: {
    marginTop: '5%',
    marginHorizontal: '5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 13,
  },
  inputConttainer: {
    marginTop: '2.5%',
  },
  inputConttainer1: {
    marginTop: '2%',
    marginBottom: -20,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '72.5%',
  },
  grayText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    // marginLeft: '2%',
  },
  rowContainer: {
    marginTop: '5%',
    marginBottom: -10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  box: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 19,
    borderColor: 'white',
    borderWidth: 2,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.BUTTON_COLOR,
  },
  rowContainer1: {
    flexDirection: 'row',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'white',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'white',
  },
  dropDownContainerStyle: {
    backgroundColor: 'white',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 150,
    height: 40,
  },

  option: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  emptyContainer: {
    backgroundColor: themeStyle.COLOR_WHITE,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    marginHorizontal: 30,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: 'lightgray',
  },
  desc1: {
    // marginLeft: '2%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  defaultProfile: {
    backgroundColor: '#F9F9F9',
    borderColor: themeStyle.YELLOW,
    borderWidth: 1,
    alignSelf: 'flex-start',
    paddingTop: 12,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 50,
  },
  bioInputContainer: {
    height: 100,
    borderWidth: 2,
    borderColor: themeStyle.COLOR_SILVER,
    borderRadius: 10,
    paddingHorizontal: 17,
    paddingTop: 5,
    marginTop: 10,
  },
  badgeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  badgeItem: {
    height: 31,
    paddingHorizontal: 17,
    backgroundColor: themeStyle.CYAN_BLUE,
    marginRight: 8,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  badgeUnselectedItem: {
    height: 31,
    paddingHorizontal: 17,
    backgroundColor: themeStyle.COLOR_WHITE,
    marginRight: 8,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
    borderColor: themeStyle.CYAN_BLUE,
    borderWidth: 1,
  },
  badgeText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  badgeInfo: {
    fontSize: 14,
    color: '#959595',
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 5,
  },
  addLinkButton: {
    backgroundColor: themeStyle.CYAN_BLUE,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginTop: 10,
    width: 124,
  },
  input: {
    height: 100,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
});
