import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';
import {scaleFont} from '../../../../lib/utils/global';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerBtn: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: themeStyle.BAR_COLOR,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: '2.5%',
  },
  btnText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: scaleFont(12),
    marginLeft: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
  },
  imageStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    height: 428,
    width: SCREEN_WIDTH,
  },
  nameText: {
    fontSize: scaleFont(16),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    marginBottom: 8,
  },
  whiteText: {
    marginLeft: 5,
    fontSize: scaleFont(10),
    color: 'white',
  },
  grayText: {
    fontSize: scaleFont(14),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayText3: {
    fontSize: scaleFont(8.5),
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK_LIGHT,
  },
  grayText1: {
    fontSize: scaleFont(10),
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingVertical: '5%',
    paddingHorizontal: '5%',
  },
  blueText: {
    fontSize: scaleFont(16),
    color: 'blue',
    fontFamily: themeStyle.FONT_REGULAR,
    textDecorationLine: 'underline',
  },
  blackText: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_BOLD,
    marginLeft: 5,
  },
  pollDescription: {
    marginTop: 24,
    fontSize: scaleFont(16),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  rowContainer: {
    marginHorizontal: '5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  adContainer: {
    marginVertical: '3%',
    backgroundColor: 'white',
    paddingVertical: '5%',
  },
  rowButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: '5%',
    marginBottom: '2.5%',
  },
  centeredContaienr: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon_text_style: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  impressionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 3,
  },
  highFiveContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 5,
  },
  impressionsText: {
    fontSize: scaleFont(14),
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.BUTTON_COLOR,
    marginLeft: 5,
  },
  searchContainer: {
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: themeStyle.SLATE_GRAY,
    flexDirection: 'row',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.85,
    paddingHorizontal: 12,
    height: 60,
    borderRadius: 10,
  },
  postLine: {
    borderBottomWidth: 1,
    borderBottomColor: 'lightgray',
    backgroundColor: 'white',
  },
  pollContainer: {
    paddingHorizontal: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 10,
    borderColor: themeStyle.CYAN_BLUE,
    paddingVertical: 15,
    marginTop: 10,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    marginTop: 24,
  },
  pollText: {
    fontSize: scaleFont(16),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  options: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    height: 46,
    justifyContent: 'center',
  },
  optionNumber: {
    backgroundColor: themeStyle.CYAN_BLUE,
    justifyContent: 'center',
    height: 40,
    borderRadius: 6,
    position: 'absolute',
    left: 1,
  },
  optionText: {
    fontSize: scaleFont(16),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingLeft: 12,
  },
  optionTitle: {
    fontSize: scaleFont(24),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
    paddingLeft: 12,
  },
  percentageContainer: {
    height: 40,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    flex: 1,
  },
  linkContainer: {
    backgroundColor: themeStyle.CYAN_BLUE,
    paddingHorizontal: 10,
    height: 55,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginTop: -10,
    justifyContent: 'center',
  },
  linkInnerContainer: {
    borderWidth: 1,
    borderColor: themeStyle.COLOR_WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 10,
    height: 36,
    borderRadius: 8,
  },
  linkText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: scaleFont(16),
    fontFamily: themeStyle.FONT_REGULAR,
  },
  sharedByContainer: {
    alignItems: 'center',
    marginLeft: 5,
  },
  sharedByText: {
    fontSize: scaleFont(10),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
  },
  sharedByUserName: {
    fontSize: scaleFont(10),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  text: {
    fontSize: scaleFont(16),
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  readMore: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: themeStyle.FONT_SIZE_SMALL,
    marginTop: 5,
  },
  linkContainer2: {
    marginHorizontal: '2.5%',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    justifyContent: 'space-between',
  },
  userTag: {marginTop: 20, marginBottom: 8},
  userTagText: {
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.COLOR_BLACK,
    fontSize: scaleFont(12),
  },
  marginLeft8: {
    marginLeft: 8,
  },
  flexDirectionRow: {
    flexDirection: 'row',
  },
  userTagContainer: {
    paddingHorizontal: '5%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH,
  },
});
