import { StyleSheet } from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerBtn: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: themeStyle.BAR_COLOR,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  btnText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 12,
    marginLeft: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {
    flex: 1,
  },
  heading: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  btnContainer: {
    flex: 0.2,
    justifyContent: 'center',
    backgroundColor: 'white',
    paddingHorizontal: '10%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desc: {
    // marginTop: '5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  inputConttainer: {
    marginTop: '2.5%',
    // height: 100,
    // backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  grayText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  rowContainer: {
    marginTop: '2.5%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  box: {
    height: 50,
    width: 165,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: themeStyle.CLASSIFIED_HOME,
    backgroundColor: themeStyle.COLOR_WHITE,
  },
  selectedbox: {
    height: 50,
    width: 165,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: themeStyle.CLASSIFIED_HOME,
  },
  rowContainer1: {
    flexDirection: 'row',
  },
  row: {
    flex: 0.37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'gray',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'white',
  },
  dropDownContainerStyle: {
    backgroundColor: 'white',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 100,
    height: 40,
  },

  option: {
    fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  option1: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    // fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  addMediaStyle: {
    flexDirection: 'row',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F8F8',
    borderRadius: 15,
  },
  addMediaStyle1: {
    padding: '5%',
    backgroundColor: 'lightgray',
    borderRadius: 15,
  },
  postImagesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: 10,
    alignSelf: 'center',
    maxWidth: 350,
    justifyContent: 'space-evenly',
  },
  postImage: {
    width: 100,
    height: 100,
    borderColor: '#BBBAB9',
    borderWidth: 1,
    backgroundColor: 'grey',
    resizeMode: 'center',
    overflow: 'hidden',
  },
  postImageLast: {
    width: 100,
    height: 100,
    borderColor: '#BBBAB9',
    borderWidth: 1,
    resizeMode: 'center',
    opacity: 0.7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inputConttainer1: {
    // marginTop: '2.5%',
    // padding: "5%",
    // height: 45,
    backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
  inputConttainer2: {
    marginTop: "2.5%",
    height: 50,
    paddingHorizontal: "2.5%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 10,
    borderColor: themeStyle.CLASSIFIED_HOME,
    borderWidth: 2
  },
  inputStyle1: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '2.5%',
  },

  selectedbox1: {
    height: 19,
    width: 19,
    borderColor: 'white',
    borderWidth: 2,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.CLASSIFIED_HOME,
  },
  selectedOption1: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  box1: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  desc1: {
    marginHorizontal: '2.5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12
  },
  desc2: {
    paddingHorizontal: '2.5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12
  },
  inputContainerStylePrice: {
    borderWidth: 2,
    borderBottomWidth: 2,
    borderColor: themeStyle.CLASSIFIED_HOME,
    backgroundColor: 'transparent',
    borderRadius: 10,
    margin: 0,
    paddingLeft: 0,
  },
  inputStylePrice: {
    fontSize: 14,
    marginLeft: '2.5%',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  containerStyle: {
    height: null,
    marginBottom: 0,
    paddingHorizontal: 0,
    borderColor: themeStyle.COLOR_WHITE,
  },
});
