import {StyleSheet} from 'react-native';
import themeStyle from '../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    backgroundColor: themeStyle.PRIMARY_BACKGROUND_COLOR,
    borderRadius: 10,
    padding: '5%',
    elevation: 0.5,
    shadowColor: themeStyle.BLACK,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 2,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowContainer1: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  image: {
    height: 65,
    width: 85,
    borderRadius: 8,
    marginRight: 10,
    marginVertical: 8,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: themeStyle.EDUCATION_BROWN,
  },
  btnContainer: {
    marginTop: '2.5%',
    height: 30,
    width: SCREEN_WIDTH * 0.3,
    backgroundColor: '#1DD1A1',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnContainer1: {
    marginTop: '2.5%',
    flexDirection: 'row',
    height: 30,
    width: SCREEN_WIDTH * 0.35,
    backgroundColor: themeStyle.EDUCATION_BROWN,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnContainerDetails: {
    marginTop: '2.5%',
    flexDirection: 'row',
    height: 33,
    width: '100%',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: themeStyle.EDUCATION_BROWN,
    borderWidth: 2,
  },

  btnContainer2: {
    marginTop: '2.5%',
    height: 30,
    width: SCREEN_WIDTH * 0.3,
    backgroundColor: '#99CC66',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowStyle: {
    flexDirection: 'row',
    // alignItems: "center"
  },
  grayTextStyle: {
    fontSize: 10,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  grayTextStyle1: {
    fontSize: 14,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  grayText: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
  },
  blackText: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
  },
  colorText: {
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#1DD1A1',
  },
  textStyle: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#313131',
  },
  pollContainer: {
    paddingHorizontal: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 10,
    borderColor: themeStyle.EDUCATION_BROWN,
    paddingVertical: 15,
    marginTop: 10,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    marginTop: 24,
  },
  pollText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  options: {
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: '#F3F3F3',
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    height: 46,
    justifyContent: 'center',
  },
  optionNumber: {
    backgroundColor: themeStyle.EDUCATION_BROWN,
    justifyContent: 'center',
    height: 40,
    borderRadius: 6,
    position: 'absolute',
    left: 1,
  },
  textChoiceContainer: {
    height: 40,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    flex: 1,
  },
  optionText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingLeft: 12,
  },
  optionTitle: {
    fontSize: 24,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
    paddingLeft: 12,
  },
  buttonContainer: {
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: themeStyle.EDUCATION_BROWN,
    paddingHorizontal: 9,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 9,
  },
  text: {
    marginLeft: 8,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
});
