import {StyleSheet} from 'react-native';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../lib/utils/constants';
import themeStyle from '../../../assets/styles/theme.style';

export default StyleSheet.create({
  carousel: {
    marginTop: 7,
  },
  gif: {
    width: SCREEN_WIDTH * 0.87,
    height: SCREEN_HEIGHT * 0.15,
    alignSelf: 'center',
  },
  descStyle: {
    fontSize: 10,
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_BLACK,
    marginTop: '1%',
    width: '98%',
    textAlign: 'justify',
    alignSelf: 'flex-start',
    marginLeft: 15,
    marginBottom: 5,
  },
  paginationContainer: {
    position: 'absolute',
    top: '70%',
    alignSelf: 'center',
  },
  dotStyle: {
    width: 50,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  inactiveDotStyle: {
    width: 20,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  title: {
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 24,
    color: themeStyle.YELLOW,
    marginTop: 13,
    alignSelf: 'center',
    textAlign: 'center',
  },
  line: {
    marginVertical: 7,
    alignSelf: 'center',
    width: 150,
    height: 1,
    backgroundColor: themeStyle.CYAN_BLUE,
  },
  image: {
    height: 200,
    width: 200,
    resizeMode: 'cover',
    alignSelf: 'center',
  },
  description: {
    paddingHorizontal: 25,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  okButton: {
    width: 140,
    height: 45,
    backgroundColor: themeStyle.CYAN_BLUE,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 20,
  },
  ok: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 16,
  },
  text: {
    textAlign: 'center',
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
    fontSize: 14,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  closeBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    position: 'absolute',
    right: 10,
  },
  rowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBanner: {
    width: SCREEN_WIDTH - 30,
    aspectRatio: 194 / 63,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    alignSelf: 'flex-start',
  },
  bottomBanner: {
    width: SCREEN_WIDTH - 30,
    aspectRatio: 194 / 63,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignSelf: 'flex-start',
  },
});
