import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';
import {scaleFont} from '../../../../lib/utils/global';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  container: {
    flex: 1,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 5,
  },
  row1: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  row2: {
    flexDirection: 'row',
  },
  rowContainer: {
    padding: '5%',
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  rowContainer1: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  rowStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.BUTTON_COLOR,
    borderRadius: 10,
    marginTop: '5%',
    width: SCREEN_WIDTH * 0.55,
    height: 40,
  },
  icon_text_style: {
    color: '#959FAE',
    fontSize: 13,
    textAlign: 'center',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  sendButtonStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.BUTTON_COLOR,
    borderRadius: 10,
    paddingHorizontal: '10%',
    height: 40,
    width: SCREEN_WIDTH * 0.55,
  },
  followingButtonStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.CYAN_BLUE,
    borderRadius: 10,
    // paddingHorizontal: "20%",
    height: 40,
    width: '55%',
    marginRight: '3%',
  },
  tabStyle: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuButton: {
    backgroundColor: 'lightgray',
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.15,
    height: 40,
    borderRadius: 10,
  },
  acceptButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.265,
    height: 40,
    borderRadius: 10,
    backgroundColor: themeStyle.CYAN_BLUE,
    color: themeStyle.COLOR_WHITE,
  },
  deleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.265,
    height: 40,
    borderRadius: 10,
    backgroundColor: themeStyle.GRAY,
    color: themeStyle.DARK_GRAY,
  },
  profileName: {
    fontSize: 22,
    fontFamily: themeStyle.FONT_BOLD,
    color: '#38474F',
    width: SCREEN_WIDTH * 0.5,
    textAlign: 'center',
  },
  btnText: {
    color: 'white',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  accetp_delete_btn_text: {
    fontFamily: themeStyle.FONT_MEDIUM,
    lineHeight: 24,
  },

  grayTier: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textTransform: 'capitalize',
    color: '#959FAE',
  },
  graybtnText: {
    color: '#959FAE',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  following: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontWeight: '500',
    lineHeight: 24,
  },
  grayTier1: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    textTransform: 'capitalize',
    color: themeStyle.CYAN_BLUE,
  },
  grayTier2: {
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 22,
    color: themeStyle.CYAN_BLUE,
  },
  buttonContainer: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    height: 40,
    width: '20%',
  },
  descContainer: {
    paddingHorizontal: '5%',
    borderBottomWidth: 1,
    borderTopWidth: 1,
    borderColor: themeStyle.COLOR_LIGHT_GREY,
  },
  // descText: {
  //   color: '#313131',
  //   fontSize: 14,
  //   marginTop: 5,
  //   fontFamily: themeStyle.FONT_REGULAR,
  // },
  descText: {
    color: '#313131',
    fontSize: 16,
    marginBottom: 8,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingHorizontal: '5%',
    lineHeight: 22,
  },
  nameText: {
    fontSize: 15,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    marginBottom: 8,
  },
  whiteText: {
    marginLeft: 5,
    fontSize: 10,
    color: 'white',
  },
  grayText: {
    fontSize: 14,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  description: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blackText: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_BOLD,
  },
  imageStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    height: SCREEN_HEIGHT * 0.35,
    width: SCREEN_WIDTH,
    padding: 10,
  },
  blueText: {
    fontSize: 10,
    color: 'blue',
    fontFamily: themeStyle.FONT_REGULAR,
    textDecorationLine: 'underline',
  },
  impressionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 10,
    height: 34,
  },
  impressionsText: {
    fontSize: scaleFont(14),
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_BLACK,
    marginLeft: 5,
  },
  searchContainer: {
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: themeStyle.SLATE_GRAY,
    flexDirection: 'row',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.85,
    paddingHorizontal: 12,
    height: 60,
    borderRadius: 10,
  },
  badgeContainer: {
    width: 70,
    height: 25,
    backgroundColor: themeStyle.CYAN_BLUE,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  badgeText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  socialIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
  },
  linksContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: '5%',
  },
  pollContainer: {
    paddingHorizontal: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 10,
    borderColor: themeStyle.CYAN_BLUE,
    paddingVertical: 15,
    marginTop: 10,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
  },
  postLine: {
    borderBottomWidth: 1,
    borderBottomColor: 'lightgray',
    backgroundColor: 'white',
  },
  pollContainer: {
    paddingHorizontal: 12,
    backgroundColor: 'white',
    borderRadius: 16,
    borderWidth: 10,
    borderColor: themeStyle.CYAN_BLUE,
    paddingVertical: 15,
    marginTop: 10,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    paddingHorizontal: 15,
    paddingVertical: 14,
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    marginTop: 24,
  },
  pollText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  options: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    backgroundColor: '#F3F3F3',
    borderRadius: 7,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
    height: 46,
    justifyContent: 'center',
  },
  optionNumber: {
    backgroundColor: themeStyle.CYAN_BLUE,
    justifyContent: 'center',
    height: 40,
    borderRadius: 6,
    position: 'absolute',
    left: 1,
  },
  optionText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    paddingLeft: 12,
  },
  optionTitle: {
    fontSize: 24,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
    paddingLeft: 12,
  },
  percentageContainer: {
    height: 40,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    flex: 1,
  },
  linkContainer: {
    backgroundColor: themeStyle.CYAN_BLUE,
    paddingHorizontal: 10,
    height: 55,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    marginTop: -10,
    justifyContent: 'center',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: '2.5%',
  },
  pollDescription: {
    marginTop: 24,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  highFiveContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderRadius: 4,
    marginRight: 10,
    height: 43,
  },
  linkInnerContainer: {
    borderWidth: 1,
    borderColor: themeStyle.COLOR_WHITE,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    paddingHorizontal: 10,
    height: 36,
    borderRadius: 8,
  },
  linkText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  sharedByContainer: {
    alignItems: 'center',
    marginLeft: 5,
  },
  sharedByText: {
    fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_BOLD,
  },
  sharedByUserName: {
    fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: -3,
  },
  text: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  leftIcon: {marginLeft: 15},
  readMore: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: themeStyle.FONT_SIZE_SMALL,
    marginTop: 5,
  },
  editPhotoButton: {
    zIndex: 1,
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: themeStyle.YELLOW,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: 30,
    width: 30,
  },
  userDetailsContainer: {
    marginLeft: '5%',
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'column',
  },
  countContainer: {alignItems: 'center', marginRight: 10},
  alignCenter: {alignItems: 'center'},
  marginTop40: {
    marginTop: '40%',
  },
  textAlignCenter: {
    textAlign: 'center',
  },
  mediaPostContainer: {
    borderBottomWidth: 5,
    borderBottomColor: 'lightgray',
    backgroundColor: 'white',
  },
  mediaPostInnerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: '5%',
    paddingVertical: '2.5%',
  },
  mediaPostProfileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  marginLeft5: {marginLeft: '5%'},
  descriptionContainer: {
    paddingVertical: '2%',
    paddingHorizontal: '4.5%',
  },
  tagUserContainer: {
    paddingHorizontal: '5%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH,
  },
  bottomButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: '3%',
    justifyContent: 'space-between',
    marginLeft: 10,
  },
  marginLeft8: {
    marginLeft: 8,
  },
  marginRight5: {
    marginRight: 5,
  },
  tagUsers: {
    marginTop: 20,
    marginBottom: 8,
  },
  listPostContainer: {backgroundColor: 'gray', margin: 1},
  mdCopyContainer: {
    position: 'absolute',
    zIndex: 1,
    alignSelf: 'flex-end',
    right: 5,
  },
  image: {
    height: SCREEN_WIDTH * 0.3,
    width: SCREEN_WIDTH * 0.329,
  },
  modalStyle: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  modalContainer: {
    backgroundColor: 'white',
    height: SCREEN_HEIGHT * 0.6,
    borderRadius: 10,
  },
  dropDown: {alignSelf: 'center', marginVertical: 15},
  search: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    width: SCREEN_WIDTH * 0.85,
    alignSelf: 'center',
    marginBottom: 10,
  },
  chatIconContainer: {
    padding: 10,
    borderRadius: 10,
    marginHorizontal: '2%',
  },
});
