import {StyleSheet} from 'react-native';
import themeStyle from '../../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../../lib/utils/constants';

export default StyleSheet.create({
  headerTitleText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  endButton: {
    backgroundColor: themeStyle.ORANGE_DARK,
    height: 35,
    borderRadius: 11,
    justifyContent: 'center',
    alignItems: 'center',
    width: 110,
  },
  endDayText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  leftIcon: {
    paddingLeft: 15,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    fontFamily: themeStyle.FONT_MEDIUM,
    marginTop: 15,
    marginHorizontal: 23,
    alignSelf: 'flex-start',
    fontSize: 16,
  },
  headerDay: {
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 10,
    marginLeft: 20,
  },
  headerDayText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  question: {
    backgroundColor: themeStyle.COLOR_MENTAL,
    width: '100%',
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingBottom: 20,
    marginTop: 15,
    marginBottom: 5,
    borderRadius: 10,
  },
  questionTitle: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_BOLD,
    color: themeStyle.COLOR_BLACK,
  },
  questionText: {
    marginTop: 5,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
  },
  answer: {
    backgroundColor: themeStyle.COLOR_MENTAL,
    width: '100%',
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingBottom: 0,
    borderRadius: 10,
  },
  answerText: {
    fontFamily: themeStyle.FONT_BOLD,
    marginBottom: 5,
    fontSize: 16,
  },
  optionContainer: {
    backgroundColor: themeStyle.COLOR_MENTAL,
    width: '99%',
    paddingHorizontal: 5,
    paddingTop: 5,
    paddingBottom: 10,
    marginTop: 5,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
  },
  optionBox: {
    width: 20,
    height: 20,
    borderColor: themeStyle.MENTAL_DARK,
    borderWidth: 2,
    borderRadius: 3,
    marginRight: 20,
  },
  multipleChoiceContainer: {
    width: '100%',
    backgroundColor: '#F8F8F8',
    paddingBottom: 15,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 5,
    marginHorizontal: 10,
    alignSelf: 'center',
  },
  multipleChoiceItem: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  multipleChoiceItemText: {
    height: 20,
    width: 70,
    borderRadius: 12,
    alignItems: 'center',
  },
  contentContainer: {
    borderColor: themeStyle.COLOR_YELLOWISH,
    backgroundColor: themeStyle.ORANGE_LIGHT,
    borderWidth: 2,
    borderRadius: 10,
    margin: 15,
    paddingHorizontal: 13,
    paddingVertical: 10,
    width: SCREEN_WIDTH - 46,
  },
  contentContainerText: {
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
  },
  readMore: {
    color: themeStyle.PURPLE_COLOR,
    marginTop: 5,
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 16,
  },
  hrFull: {
    borderWidth: 0.5,
    borderColor: themeStyle.MENTAL_LIGHT,
    // height: 20,
    width: '100%',
  },
  Day9Container: {
    backgroundColor: themeStyle.COLOR_MENTAL,
    width: '92%',
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 5,
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
  },
  Day16Container: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
  supporters: {
    backgroundColor: '#F8F8F8',

    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingVertical: 10,
  },
  supportersText: {
    backgroundColor: '#F8F8F8',
    borderRadius: 10,
    marginTop: 10,
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  day17Container: {
    width: '90%',
    backgroundColor: '#F8F8F8',
    padding: 10,
    borderRadius: 10,
    marginTop: 20,
  },

  hr70: {
    borderWidth: 0.5,
    borderColor: themeStyle.MENTAL_LIGHT,
    alignSelf: 'center',
    width: '70%',
    marginTop: 10,
  },

  TwentyEightContainer: {
    width: '90%',
    backgroundColor: '#F8F8F8',
    padding: 10,
    borderRadius: 10,
    marginTop: 20,
  },
  ButtonEnd: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingRight: 8,
    marginTop: 20,
  },
  completedContainer: {
    flex: 1,
    backgroundColor: themeStyle.COLOR_WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '-30%',
  },
  congratulations: {
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 30,
    paddingHorizontal: 25,
    color: themeStyle.COLOR_BLACK,
    textAlign: 'center',
  },
  completedText: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 18,
    color: themeStyle.COLOR_BLACK,
    paddingHorizontal: 25,
    textAlign: 'center',
    marginTop: 15,
  },
  bold: {
    fontFamily: themeStyle.FONT_BOLD,
  },
  rewardIcon: {
    width: 200,
    height: 200,
  },
});
