import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  buttonStyleDone: {
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeStyle.MENTAL_LIGHT,
    height: SCREEN_HEIGHT * 0.075,
    marginBottom: '10%',
    width: SCREEN_WIDTH * 0.3,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    elevation: 0,
    backgroundColor: themeStyle.ORANGE_LIGHT,
  },
  nextExercise: {
    marginHorizontal: '5%',
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  headerDay: {
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 10,
    marginLeft: 20,
  },
  headerDayText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headerTitleText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  playButtonContainer: {
    backgroundColor: themeStyle.WHITE_SMOKE,
    width: 70,
    height: 130,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playText: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
    color: themeStyle.COLOR_BLACK_LIGHT,
    marginTop: 8,
  },
  modalContainer: {
    height: SCREEN_HEIGHT * 0.4,
    alignSelf: 'center',
    backgroundColor: themeStyle.COLOR_LIGHT_GREY,
    width: SCREEN_WIDTH * 1,
    flexDirection: 'row',
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerBtn: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: themeStyle.BAR_COLOR,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  btnText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 12,
    marginLeft: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {
    flex: 1,
    paddingTop: '5%',
  },
  contentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH,
    paddingLeft: '1%',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '2.5%',
    marginVertical: '2.5%',
    marginBottom: '5%',
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
  },
  btnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#38474F',
    paddingVertical: '2.5%',
    paddingHorizontal: '14%',
    borderRadius: 10,
  },
  textStyleMenu: {
    fontFamily: themeStyle.FONT_BOLD,
    width: '70%',
    color: themeStyle.PURPLE_COLOR,
    fontSize: 40,
  },
  textStyleMenu2: {
    fontFamily: themeStyle.FONT_REGULAR,
    width: '70%',
    color: themeStyle.COLOR_BLACK_LIGHT,
    fontWeight: '700',
    fontSize: 11,

    // textDecorationLine: 'underline',
  },
  textStyle: {
    fontSize: 15,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK_LIGHT,
  },
  textStylebutton: {
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK_LIGHT,
  },
});
