import {StyleSheet} from 'react-native';
import themeStyle from '../../../../../assets/styles/theme.style';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  title: {
    color: themeStyle.PURPLE_COLOR,
    fontSize: 32,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 30,
    marginLeft: 20,
  },
  noGoals: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 20,
    marginLeft: 20,
    textAlign: 'center',
  },
  loader: {
    marginTop: '30%',
  },
  termTitle: {
    color: themeStyle.PURPLE_COLOR,
    fontSize: 24,
    fontFamily: themeStyle.FONT_BOLD,
    marginLeft: 20,
    marginTop: 28,
  },
  goal: {
    fontFamily: themeStyle.FONT_BOLD,
  },
  lifeGoals: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: 20,
    marginTop: 2,
  },
  createGoal: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    marginTop: 15,
    marginLeft: 20,
  },
  createButton: {
    backgroundColor: themeStyle.PURPLE_COLOR,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginHorizontal: 20,
  },
  selected: {
    height: 40,
    borderRadius: 3,
    backgroundColor: themeStyle.ORANGE_DARK,
    justifyContent: 'center',
    alignItems: 'center',
    width: '33%',
  },
  selectedText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 12,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  notSelected: {
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    width: '33%',
  },
  notSelectedText: {
    color: '#929398',
    fontSize: 12,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  selectedGoalDetails: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 8,
    color: '#777777',
    marginLeft: 20,
  },
  createGoalText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 8,
    backgroundColor: themeStyle.COLOR_LIGHT_GREY,
    paddingHorizontal: 6,
    paddingVertical: 6,
    borderRadius: 4,
  },
  goalsList: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    marginTop: 12,
    marginLeft: 20,
  },
  goalsListContainer: {
    marginTop: 10,
    marginHorizontal: 20,
    backgroundColor: themeStyle.WHITE_SMOKE,
    paddingTop: 20,
    paddingBottom: 24,
    elevation: 1,
    borderRadius: 10,
  },
  dateRange: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    marginLeft: 11,
  },
  goalListRowContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 28,
    marginLeft: 5,
    paddingHorizontal: 24,
  },
  goalText: {
    color: themeStyle.INPUT_PRIMARY_TEXT_COLOR,
    fontSize: 14,
    fontFamily: themeStyle.FONT_MEDIUM,
    width: '82%',
  },
  yourProgress: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    marginTop: 12,
    marginLeft: 20,
  },
  progressContainer: {
    marginHorizontal: 20,
    borderRadius: 10,
    marginVertical: 6,
    flexDirection: 'row',
  },
  completedProgress: {
    flex: 1,
    paddingVertical: 13,
    backgroundColor: themeStyle.ORANGE_DARK,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inProgress: {
    flex: 1,
    paddingVertical: 13,
    backgroundColor: '#FF9C53',
    justifyContent: 'center',
    alignItems: 'center',
  },
  allGoals: {
    flex: 1,
    paddingVertical: 13,
    backgroundColor: themeStyle.COLOR_YELLOWISH,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  progressPercentage: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 20,
    fontFamily: themeStyle.FONT_BOLD,
  },
  infoRow: {
    flexDirection: 'row',
  },
  box: {
    width: 10,
    height: 10,
    marginRight: 6,
  },
  row: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
