import {StyleSheet, Platform} from 'react-native';
import themeStyle from '../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../lib/utils/constants';

export default StyleSheet.create({
  inputBoxView: {
    backgroundColor: 'white',
    borderRadius: 10,
    paddingTop: Platform.OS === 'android' ? 0 : 3,
    paddingBottom: Platform.OS === 'android' ? 0 : 3,
    overflow: 'hidden',
    width: '80%',
    marginRight: 5,
    marginLeft: 5,
    paddingRight: 10,
    paddingLeft: 10,
    // paddingVertical: '5%',
    // minHeight: 47,
  },
  commentInput: {
    color: 'black',
    fontSize: 14,
    lineHeight: 18,
    flex: 1,
    paddingTop: 12,
    paddingBottom: 10,

    // maxHeight: 150,
  },
  nameText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_BOLD,
  },
  balloon: {
    alignSelf: 'baseline',
    paddingHorizontal: 5,
    paddingTop: 5,
    paddingBottom: 5,
    borderRadius: 10,
    maxWidth: '80%',
    minWidth: '20%',
    marginRight: 13,
  },
  item: {
    letterSpacing: 0.5,
    fontFamily: themeStyle.FONT_REGULAR,
    lineHeight: 20,
    padding: 10,
    fontSize: 14,
    // color: ,
    flex: 1,
  },
  itemText1: {
    fontSize: 10,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_WHITE,
    textAlign: 'center',
  },
  seperatorStyle: {
    height: 15,
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  attachment: {
    // flexDirection: 'row',
    // alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor: 'white',
    borderRadius: 30,
    // marginRight: 10,
    // marginLeft: 10,
    // paddingTop: 10,
    marginBottom: 15,
  },
  itemContainer: {
    flexDirection: 'row',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    padding: 10,
    overflow: 'hidden',
    marginBottom: '2.5%',
    marginHorizontal: '4%',
  },
  grayText: {
    fontSize: 10,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayText1: {
    fontSize: 10,
    marginTop: 5,
    width: SCREEN_WIDTH * 0.5,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blackText: {
    marginLeft: 10,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blackText2: {
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blackText1: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  rowStyle: {
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  rowStyle1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lowerContainer: {
    justifyContent: 'space-between',
    padding: '2.5%',
  },
  imageStyle: {
    height: 75,
    width: 100,
  },
  footerIcon: {
    borderRadius: 10,
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tick: {
    color: themeStyle.COLOR_BOOK_KEEPING,
  },
  reactionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '70%',
    alignItems: 'center',
    position: 'absolute',
    backgroundColor: 'white',
    height: 40,
    paddingHorizontal: 10,
    borderRadius: 10,
    bottom: 0,
    left: 14,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    zIndex: 1000,
  },
  audioContainer: {
    marginTop: 5,
    padding: 10,
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  noMessageContainer: {
    flex: 1,
    transform: [{scaleY: -1}],
    justifyContent: 'center',
    alignItems: 'center',
  },
  noMessage: {fontFamily: themeStyle.FONT_REGULAR},
  listViewProps: {marginTop: '7%', marginBottom: '1.5%'},
  mic: {
    marginLeft: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 40,
    paddingBottom: 10,
  },
  add: {
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    width: 40,
    paddingBottom: 10,
  },
  inputContainer: {
    backgroundColor: 'white',
    borderWidth: 2,
    borderRadius: 10,
    borderTopWidth: 2,
    borderColor: '#777777',
    justifyContent: 'center',
    marginBottom: -20,
  },
  textInputStyle: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {flex: 1},
  inputToolbarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    borderRadius: 5,
    marginHorizontal: 10,
    height: 52,
    paddingBottom: 25,
    marginBottom: 10,
  },
  alignEnd: {alignItems: 'flex-end'},
  paddingTop: {
    paddingTop: '2.5%',
  },
  education: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 15,
  },
});
