import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT, SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  container: {
    flex: 1,
  },
  rowContainer: {
    padding: '5%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowContainer1: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '5%',
    marginTop: '3%',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileName: {
    fontSize: 20,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
    marginLeft: 8,
  },
  rowStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.BUTTON_COLOR,
    borderRadius: 10,
    marginTop: '5%',
    width: SCREEN_WIDTH * 0.55,
    height: 40,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: themeStyle.CARRER_SECONDARY,
    marginTop: '5%',
    marginLeft: 20,
  },

  icon_text_style: {
    color: '#959FAE',
    fontSize: 13,
    textAlign: 'center',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  sendButtonStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.BUTTON_COLOR,
    borderRadius: 10,
    paddingHorizontal: '10%',
    height: 40,
  },
  followingButtonStyle: {
    marginTop: '10%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    paddingHorizontal: '20%',
    height: 40,
  },
  tabStyle: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuButton: {
    backgroundColor: 'lightgray',
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.15,
    height: 40,
    borderRadius: 10,
  },
  acceptButton: {
    backgroundColor: 'lightgray',
    justifyContent: 'center',
    alignItems: 'center',
    width: SCREEN_WIDTH * 0.265,
    height: 40,
    borderRadius: 10,
  },
  btnText: {
    color: 'white',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayTier: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textTransform: 'capitalize',
    color: '#959FAE',
  },
  graybtnText: {
    color: '#959FAE',
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  grayTier1: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textTransform: 'capitalize',
    color: '#959FAE',
  },
  grayTier2: {
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 22,
    color: '#959FAE',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
    backgroundColor: 'lightgray',
    paddingVertical: '2.5%',
    paddingHorizontal: '5%',
  },
  descContainer: {
    paddingHorizontal: '5%',
    paddingVertical: '2.5%',
    borderBottomWidth: 0.5,
    borderTopWidth: 0.5,
    borderColor: 'lightgray',
  },
  descText: {
    color: '#313131',
    fontSize: 12,
    marginTop: 5,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  nameText: {
    // fontSize: 10,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  whiteText: {
    marginLeft: 5,
    fontSize: 10,
    color: 'white',
  },
  grayText: {
    fontSize: 10,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  blackText: {
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_BOLD,
  },
  imageStyle: {
    flex: 1,
    justifyContent: 'flex-end',
    height: SCREEN_HEIGHT * 0.35,
    width: SCREEN_WIDTH,
    padding: 10,
  },
  text: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 3,
    textTransform: 'capitalize',
  },
  noAppliedText: {
    fontSize: 15,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK,
    textAlign: 'center',
    marginTop: '20%',
  },
  savedJobsButton: {
    backgroundColor: themeStyle.CARRER_SECONDARY,
    paddingVertical: 12,
    borderRadius: 10,
    width: 180,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    marginTop: 12,
  },
  searchJobs: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  appliedJobs: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    marginLeft: '5%',
    marginTop: '6%',
    marginBottom: '3%',
  },
});
