import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    flex: 0.82,
  },
  selfieWarning: {flexDirection: 'row', alignItems: 'center', marginTop: 3},
  imageContainer: {
    borderWidth: 2,
    borderColor: themeStyle.PINK,
    height: 92,
    width: 92,
    borderRadius: 46,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 5,
  },
  selfie: {
    borderWidth: 3,
    borderColor: themeStyle.PINK,
    height: 92,
    width: 92,
    borderRadius: 46,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 5,
  },
  submitButton: {
    width: '100%',
    borderRadius: 10,
    height: 53,
    backgroundColor: themeStyle.SPANISH_PINK,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  submitText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  selfieModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  selfieImage: {
    height: 240,
    width: 240,
    borderRadius: 120,
    borderWidth: 5,
    borderColor: themeStyle.PINK,
    marginBottom: 15,
  },
  selfieDetails: {
    color: themeStyle.GRAY,
    fontFamily: themeStyle.FONT_REGULAR,
    marginBottom: 15,
  },
  selfieDetailsText: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    lineHeight: 25,
    alignSelf: 'flex-start',
  },
  retakeSelfie: {
    color: themeStyle.PINK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  selfieModal: {
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    padding: 20,
    width: SCREEN_WIDTH * 0.9,
    // height: SCREEN_HEIGHT * 0.73,
    paddingTop: 20,
    paddingBottom: 30,
    alignItems: 'center',
    elevation: 3,
    //add shadow for ios
    shadowColor: themeStyle.COLOR_BLACK,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
    borderRadius: 20,
  },
  selfieModalTitle: {
    fontSize: 32,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PINK,
    textAlign: 'center',
    marginBottom: 15,
  },
  selfieModalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  selfieModalButton: {
    backgroundColor: themeStyle.PINK,
    padding: 10,
    borderRadius: 10,
    width: '40%',
    alignItems: 'center',
  },
  modalTextRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    width: '95%',
  },
  verificationProcessText: {
    color: '#9D9D9D',
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
    textAlign: 'center',
  },
  selfieButton: {
    backgroundColor: themeStyle.SPANISH_PINK,
    borderRadius: 10,
    paddingHorizontal: 15,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
  },
  takeSelfieText: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  followSteps: {
    color: '#9F9F9F',
    fontFamily: themeStyle.FONT_REGULAR,
    marginTop: 4,
    marginBottom: 10,
  },
  addImage: {
    position: 'absolute',
    bottom: -4,
    right: 5,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heading: {
    // marginTop: "5%",
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 20,
  },
  btnContainer: {
    // flex: 0.5,
    justifyContent: 'flex-end',
    // marginTop: "15%",
    marginHorizontal: '10%',
  },
  selfieTitle: {
    color: themeStyle.PINK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    marginRight: '2%',
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rowContainer: {
    marginTop: '5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  row: {
    marginTop: '5%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  heading2: {
    marginTop: '5%',
    color: themeStyle.PINK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  desc: {
    marginTop: '1%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    fontWeight: '400',
  },
  textContainer: {
    backgroundColor: themeStyle.SPANISH_PINK,
    paddingVertical: '10%',
    paddingHorizontal: '5%',
    alignItems: 'center',
    borderRadius: 25,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  textContainer1: {
    backgroundColor: themeStyle.COLOR_WHITE,
    paddingVertical: '10%',
    paddingHorizontal: '5%',
    alignItems: 'center',
    borderRadius: 25,
    borderWidth: 2,
    borderColor: themeStyle.SPANISH_PINK,
  },
  desc1: {
    marginHorizontal: '2.5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  inputConttainer: {
    marginTop: '2.5%',
    height: 50,
    paddingHorizontal: '2.5%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
  },
  inputConttainer1: {
    marginTop: '5%',
    // backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
  contentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH * 0.9,
    paddingTop: '5%',
  },
  darkDash: {
    backgroundColor: themeStyle.PINK,
    width: 58,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: themeStyle.SPANISH_PINK,
    width: 58,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  modalContainer: {
    padding: '5%',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 15,
  },
  grayText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  grayText1: {
    color: '#959FAE',
    textAlign: 'left',
    // marginTop: "15%",
    fontSize: 18,
    // marginBottom: "5%",
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  grayText2: {
    color: '#959FAE',
    textAlign: 'left',
    // marginTop: "15%",
    fontSize: 12,
    // marginBottom: "5%",
    fontFamily: themeStyle.FONT_MEDIUM,
  },
  linkText: {
    color: '#000000',
    textAlign: 'center',
    fontSize: 14,
    fontFamily: themeStyle.FONT_BOLD,
  },
  margin: {
    marginHorizontal: '3%',
    marginTop: '5%',
  },
  headingText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 22,
  },
  heading1: {
    // marginTop: "5%",
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    fontWeight: '400',
  },
  back: {
    width: SCREEN_WIDTH * 0.415,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: themeStyle.SPANISH_PINK,
  },
  selfieBack: {
    width: SCREEN_WIDTH * 0.37,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    fontFamily: themeStyle.FONT_REGULAR,
    borderWidth: 2,
    borderColor: themeStyle.SPANISH_PINK,
  },
  takeSelfie: {
    width: SCREEN_WIDTH * 0.37,
    height: 50,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
    backgroundColor: themeStyle.SPANISH_PINK,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  next: {
    width: SCREEN_WIDTH * 0.415,
    height: 50,
    fontSize: 16,
    fontWeight: '400',
    backgroundColor: themeStyle.SPANISH_PINK,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
});
