import {cos} from 'react-native-reanimated';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_SOCIALNETWORK_USERDATA_SUCCESS =
  'USER_SOCIALNETWORK_USERDATA_SUCCESS';
export const SEND_CODE_TO_USER_PHONENUMBER_SUCCESS =
  'SEND_CODE_TO_USER_PHONENUMBER_SUCCESS';
export const IS_USER_VERIFIED_SUCCESS = 'IS_USER_VERIFIED_SUCCESS';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const TOPADS_SUCCESS = 'TOPADS_SUCCESS';
export const BOTTOMADS_SUCCESS = 'BOTTOMADS_SUCCESS';
export const LOADING_ADDRESSES_SUCCESS = 'LOADING_ADDRESSES_SUCCESS';
export const USER_UPDATE_PROFILE_INFO_SUCCESS =
  'USER_UPDATE_PROFILE_INFO_SUCCESS';
export const USER_ADD_ADDRESS_SUCCESS = 'USER_ADD_ADDRESS_SUCCESS';
export const USER_EMAIL_AND_PASSWORD_SUCCESS =
  'USER_EMAIL_AND_PASSWORD_SUCCESS';
// Addresses types for dispacthing
export const USER_ALL_ADDRESS_SUCCESS = 'USER_ALL_ADDRESS_SUCCESS';
export const USER_ADD_NEW_ADDRESS_SUCCESS = 'USER_ADD_NEW_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_SUCESS = 'DELETE_ADDRESS_SUCESS';
export const USER_EDIT_ADDRESS_SUCCESS = 'USER_EDIT_ADDRESS_SUCCESS';
export const CHANGE_DEFAULT_ADDRESS_SUCESS = 'CHANGE_DEFAULT_ADDRESS_SUCESS';

// Cart types for dispacthing
export const CART_SUCCESS = 'CART_SUCCESS';
export const REGION_SUCCESS = 'REGION_SUCCESS';
export const SUB_CATEGORIES_SUCCESS = 'SUB_CATEGORIES_SUCCESS';
export const LOADING_CATEGORIES_SUCCESS = 'LOADING_CATEGORIES_SUCCESS';
export const ALL_SERVICES_SUCCESS = 'ALL_SERVICES_SUCCESS';
// Barbers types for dispacthing
export const BARBERS_LIST_SUCCESS = 'BARBERS_LIST_SUCCESS';
export const LOADING_BARBERS_SUCCESS = 'LOADING_BARBERS_SUCCESS';

// Notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const LOADING_NOTIFICATIONS_SUCCESS = 'LOADING_NOTIFICATIONS_SUCCESS';

//HEALTH_AND_SEFATY_SUCCESS
export const HEALTH_AND_SEFATY_SUCCESS = 'HEALTH_AND_SEFATY_SUCCESS';

//CAREER_SEARCH_SUCCESS
export const CAREER_SEARCH_SUCCESS = 'CAREER_SEARCH_SUCCESS';
//CLASSIFIED_SEARCH_SUCCESS
export const CLASSIFIED_SEARCH_SUCCESS = 'HEALTH_AND_SEFATY_SUCCESS';
//CONNECT_INTERESTS_SUCCESS
export const CONNECT_INTERESTS_SUCCESS = 'CONNECT_INTERESTS_SUCCESS';
export const CONNECT_MODES_SUCCESS = 'CONNECT_MODES_SUCCESS';
export const CONNECT_PROFESSIONS_SUCCESS = 'CONNECT_PROFESSIONS_SUCCESS';

export const USER_MODULE_SUCCESS = 'USER_MODULE_SUCCESS';

export const CONNECT_PERSONALJUDGEMENT_SUCCESS =
  'CONNECT_PERSONALJUDGEMENT_SUCCESS';

export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
// Filter Type
export const POST_FILTER_UPDATE = 'POST_FILTER_UPDATE';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const NOTIFICATION_VALUE = 'NOTIFICATION_VALUE';
export const PAYMENT_STATUS = 'PAYMENT_STATUS';
export const REGION_ADD = 'REGION_ADD';
export const USER_CURRENCY = 'USER_CURRENCY';

// Pager

export const FETCH_PAGER_POST_SUCCESS = 'FETCH_PAGER_POST_SUCCESS';
export const PAGER_USER_PROFILE = 'PAGER_USER_PROFILE';
export const PAGER_PROFILE = 'PAGER_PROFILE';
export const SOCIAL_REQUEST = 'SOCIAL_REQUEST';
export const SOCIAL_LIST = 'SOCIAL_LIST';

// Social Stories

export const SOCIAL_STORIES = 'SOCIAL_STORIES';

// Mental Health
export const MENTAL_HEALTH_POSTS = 'MENTAL_HEALTH_POSTS';
export const MENTAL_HEALTH_PROFILE = 'MENTAL_HEALTH_PROFILE';
export const MENTAL_HEALTH_DIARY = 'MENTAL_HEALTH_DIARY';
export const MENTAL_HEALTH_DAYS = 'MENTAL_HEALTH_DAYS';
export const STRIPE_OBJECT_CREATE = 'STRIPE_OBJECT_CREATE';
export const JOURNAL_DAYS_SUCCESS = 'JOURNAL_DAYS_SUCCESS';
export const HEALTH_DAYS_SUCCESS = 'HEALTH_DAYS_SUCCESS';

//Splash screen
export const FETCH_MODULES_SPLASH = 'FETCH_MODULES_SPLASH';
