import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';

export default StyleSheet.create({
  container: {flex: 1},
  createPollText: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    // fontSize: 12,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  rowContainer: {
    flexDirection: 'row',
  },
  row: {
    flex: 0.3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  box: {
    height: 19,
    width: 22,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 22,
    borderRadius: 3,
    backgroundColor: themeStyle.CYAN_BLUE,
  },
  option: {
    marginLeft: 10,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    height: 50,
    textAlignVertical: 'top',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 7,
    color: themeStyle.COLOR_BLACK,
    borderTopWidth: 0.4,
  },
  title: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    marginTop: 17,
    marginBottom: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  text: {
    fontSize: 16,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  uploadButton: {
    width: '100%',
    height: 50,
    backgroundColor: themeStyle.CYAN_BLUE,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 50,
    marginBottom: 20,
  },
  uploadText: {color: themeStyle.COLOR_WHITE, fontSize: 20},
  selectFriendsInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    paddingVertical: 17,
    paddingHorizontal: 15,
    borderRadius: 7,
    justifyContent: 'space-between',
  },
  descriptionInput: {
    borderWidth: 2,
    borderColor: '#91BFE1',
    height: 140,
    textAlignVertical: 'top',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 7,
    color: themeStyle.COLOR_BLACK,
  },
  enterOptionInput: {
    textAlignVertical: 'top',
    color: themeStyle.COLOR_BLACK,
    width: '92%',
  },
  enterOptionContainer: {
    borderWidth: 2,
    borderColor: themeStyle.CYAN_BLUE,
    height: 140,
    paddingHorizontal: 18,
    borderRadius: 7,
    marginTop: 10,
    width: '100%',
    color: themeStyle.COLOR_BLACK,
  },
  linkContainer: {
    borderWidth: 2,
    borderColor: '#BBD7EC',
    height: 36,
    borderRadius: 7,
    position: 'absolute',
    bottom: 5,
    // left: 5,
    left: 10,
    right: 10,
    // width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  linkInput: {
    height: 36,
    fontSize: 14,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    justifyContent: 'center',
    width: '90%',
  },
  selectFriends: {
    color: themeStyle.INPUT_TEXT,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
});
