import {Dimensions} from 'react-native';
const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;

const screen = {
  SCREEN_TITLE_ALIGN_CENTER: 'center',
  GAMES: 'Games',
  APPGAMES: 'App Games',
  CONSOLESERVER: 'Console Servers',
  SOCIALEXPLORE: 'Explore',
  SOCIALFILTER: 'Filter',
  CAREERJOBS: 'Jobs',
  CAREERLOCUMS: 'Locums',
  SOCIALREQUEST: 'Requests',
  SOCIALFOLLOWING: 'Following',
  EDUCATIONCLASSES: 'Classes',
  EDUCATIONCME: 'CME',
  EDUCATIONCONFERENCES: 'Conferences',
};
const Fonts = {
  regular: {
    fontFamily: '',
  },
};

const route = {
  SPLASH:'Splash',
  APPPRIVACYCONSENT: 'AppPrivacyConsent',
  MENTALVIEWURL: 'MentalViewUrl',
  TERMANDCONDITIONS: 'Terms&Conditions',
  PRIVACYPOLICY: 'PrivacyPolicy',
  FAQS: 'Faqs',
  TUTORIALS: 'Tutorials',
  REVIEWAPP: 'ReviewApp',
  TUTORIALDETAIL: 'TutorialDetail',
  VIEWURL: 'ViewUrl',
  ACCOUNTSETTINGS: 'AccountSettings1st',
  ACCOUNTSETTINGS2nd: 'AccountSettings2nd',
  NOTIFICATIONSCREEN: 'NotificationScreen',
  SOCIALSETTINGS1st: 'SocialSettings1st',
  SOCIALSETTINGS2nd: 'SocialSettings2nd',
  CLASSIFIEDSETTINGS: 'ClassifiedSettings',
  GAMESSETTINGS: 'GameSettings',
  EDUCATIONSETTINGS: 'EducationSettings',
  EDUCATIONSETTINGS2nd: 'EducationSettings2nd',
  CAREERSETTINGS: 'CareerSettings',
  CONNECTSETTINGS1ST: 'ConnectSettings1st',
  CONNECTSETTINGS2ND: 'ConnectSettings2nd',
  AUTH_LOADING: 'AuthLoading',
  LOGINORSIGNUP: 'LoginOrSignup',
  CONNECTUSERPROFILE: 'ConnectUserProfile',
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  CREATEPOLL: 'CreatePoll',
  HOMESCREEN: 'HomeScreen',
  FORGOTPASSWORD: 'ForgotPassword',
  SELECTGENDER: 'SelectGender',
  UPLOADLICENSE: 'UploadLicense',
  UPLOADCNIC: 'UploadCnic',
  ADVANCEVERIFICATION: 'AdvanceVerification',
  SUCCESSFULSUBMISSION: 'SuccessfulSubmission',
  PHONENUMBER: 'PhoneNumber',
  VERIFYPHONE: 'VerifyPhone',
  WELCOME: 'Welcome',
  PROFILE: 'Profile',
  CHAT: 'Chat',
  CHATSCREEN: 'ChatScreen',
  CHATLIST: 'ChatList',
  HOME: 'Home',
  CLASSIFIEDWISHLIST: 'ClassifiedWishList',
  SELECTLOCATION: 'SelectLocation',
  NOTIFICATION: 'Notification',
  APPSETTING: 'AppSetting',
  MAIN: 'Main',
  APPSETTINGS: 'AppSettings',
  CHANGEPASSWORD:'ChangePassword',
  TWOFACTORAUTH:'TwoFactorAuth',
  OTPVERIFY:'OtpVerify',
  GAMES: 'Games',
  APPGAMES: 'AppGames',
  GAMESGIF: 'GamesGif',
  CONSOLESERVER: 'ConsoleServers',
  POSTSERVER: 'PostServer',
  POSTSERVERDETAIL: 'PostServerDetail',
  GAMESAPP: 'GamesApp',
  GAMEDETAIL: 'GameDetail',
  ALLGAMES: 'AllGames',
  LEADERBOARD: 'LeaderBoard',
  SOCIAL: 'Social',
  SOCIALHOME: 'SocialHome',
  SOCIALGIF: 'SocialGif',
  SOCIALCAMERA: 'SocialCamera',
  SOCIALPOST: 'SocialPost',
  SOCIALPOST1: 'SocialPost1',
  SOCIALSEARCH: 'SocialSearch',
  SOCIALEXPLORE: 'SocialExplore',
  SOCIALFILTER: 'SocialFilter',
  SOCIALPROFILE: 'SocialProfile',
  SOCIALSINGLEPOST: 'SocialSinglePost',
  SOCIALSAVEDPOST: 'SocialSavedPost',
  SOCIALBLOCK: 'SocialBlock',
  SOCIALFOLLOWER: 'SocialFollower',
  SOCIALFOLLOWING: 'SocialFollowing',
  SOCIALREQUEST: 'SocialRequests',
  SOCIALSPLASH: 'SocialSplash',
  // Discalimer Addition
  SOCIALDISCLAIMER: 'SocialDisclaimer',
  CAREER: 'Career',
  CAREERHOME: 'CareerHome',
  CAREERGIF: 'CareerGif',
  CAREERTIER: 'CareerTier',
  UPLOADCNICBACK: 'UploadCnicBack',
  CAREERWELCOME: 'CareerWelcome',
  CAREERVIEWAPPLICANT: 'CareerViewApplicant',
  CAREERJOBCREATE: 'CareerJobCreate',
  CAREERPROFILE: 'CareerProfile',
  CAREERJOBFAV: 'CareerJobFav',
  CAREERJOBPOSTED: 'CareerJobPosted',
  CAREERPROFILE1ST: 'CareerProfile1st',
  CAREERPROFILE2ND: 'CareerProfile2nd',
  CAREERJOBS: 'CareerJobs',
  CAREERLOCUMS: 'CareerLocums',
  CAREERSEARCH: 'CareerSearch',
  CAREERJOBDETAIL: 'CareerJobDetail',
  CAREERRESEARCHPROFILE: 'CareerResearchProfile',
  CAREERLOCUMDETAIL: 'CareerLocumDetail',
  CAREERUPLOADYOURPHOTO: 'CareerUploadYourPhoto',
  CAREERJOBAPPLIED: 'CareerJobApplied',
  CAREERSPLASH: 'CareerSplash',
  CLASSIFIED: 'Classified',
  MARKET:'Market',
  CLASSIFIEDSEARCH: 'ClassifiedSearch',
  CLASSIFIEDPOSTAD: 'ClassifiedPostAd',
  CLASSIFIEDPRODUCTCATEGORY: 'ClassifiedProductCategory',
  CLASSIFIEDPRODUCTDETAIL: 'ClassifiedProductDetail',
  CLASSIFIEDMYADS: 'ClassifiedMyAds',
  CLASSIFIEDHOME: 'ClassifiedHome',
  CLASSIFIEDGIF: 'ClassifiedGif',
  CLASSIFIEDSPLASH: 'ClasssifiedSplash',
  CONNECT: 'Connect',
  CONNECTWELCOME: 'ConnectWelcome',
  CONNECTDISCLAIMER: 'ConnectDisclaimer',
  CONNECTPROFILE1ST: 'ConnectProfile1st',
  CONNECTPROFILE2ND: 'ConnectProfile2nd',
  CONNECTPROFILE3RD: 'ConnectProfile3rd',
  CONNECTPROFILE4TH: 'ConnectProfile4th',
  CONNECTHOME: 'ConnectHome',
  CONNECTGIF: 'ConnectGif',
  CONNECTMATCHEDHISTORY: 'ConnectMatchedHistory',
  CONNECTADVANCEFILTER: 'ConnectAdvanceFilter',
  CONNECTMATCHEDPROFILE: 'ConnectMatchedProfile',
  CONNECTFAVOURITEPROFILE: 'ConnectFavouriteProfile',
  CONNECTSPLASH: 'ConnectSplash',
  EDUCATION: 'Education',
  EDUCATIONWELCOME: 'EducationWelcome',
  EDUCATIONGIF: 'EducationGif',
  EDUCATIONDISCLAIMER: 'EducationDisclaimer',
  EDUCATIONTEACHER: 'EducationTeacher',
  EDUCATIONSTUDENT: 'EducationStudent',
  EDUCATIONSTUDENTCLASSES: 'EducationStudentClasses',
  EDUCATIONSTUDENTCME: 'EducationStudentCME',
  EDUCATIONSTUDENTCONFERENCES: 'EducationStudentConferences',
  EDUCATIONTEACHERCLASSES: 'EducationTeacherClasses',
  EDUCATIONTEACHERCME: 'EducationTeacherCME',
  EDUCATIONTEACHERCONFERENCES: 'EducationTeacherConferences',
  EDUCATIONSTUDENTCLASSDETAIL: 'EducationStudentClassDetail',
  EDUCATIONSTUDENTWORKSHOPDETAIL: 'EducationStudentWorkShopDetail',
  EDUCATIONSTUDENTAPPLIEDCLASSES: 'EducationStudentAppliedClasses',
  EDUCATIONSTUDENTAPPLIEDCLASSESDETAIL: 'EducationStudentAppliedClassesDetail',
  EDUCATIONSTUDENTPOSTCLASS: 'EducationStudentPostClass',
  EDUCATIONSTUDENTCLASSESANDREQUESTS: 'EducationStudentClassesAndRequests',
  EDUCATIONSTUDENTMYCLASSES: 'EducationStudentMyClasses',
  EDUCATIONSTUDENTMYRQUESTS: 'EducationStudentMYRequests',
  EDUCATIONSTUDENTYOURCLASSEDETAIL: 'EducationStudentYourClassDetail',
  EDUCATIONTEACHERYOURCLASSEDETAIL: 'EducationTeacherYourClassDetail',
  EDUCATIONTEACHERPOSTCLASS: 'EducationTeacherPostClass',
  EDUCATIONTEACHERMYCLASSES: 'EducationTeacherMyClasses',
  EDUCATIONTEACHERMYRQUESTS: 'EducationTeacherMYRequests',
  EDUCATIONTEACHERREVIEWS: 'EducationTeacherReviews',
  EDUCATIONTEACHERSTATS: 'EducationTeacherStats',
  EDUCATIONTEACHERREADREVIEWS: 'EducationTeacherReadReviews',
  EDUCATIONTEACHERCLASSESANDREQUESTS: 'EducationTeacherClassesAndRequests',
  EDUCATIONSPLASH: 'EducationSplash',
  QR: 'Qr',
  QRCODE: 'QrCode',
  SCANQRCODE: 'ScanQrCode',
  EDUCATIONCREATEQNA: 'EducationCreateQnA',
  EDUCATIONQNADISCUSSION: 'EducationQnADiscussion',
  EDUCATIONHOME: 'EducationHome',
  SUPPORT: 'Support',

  // Wallet Addition
  WALLET: 'Wallet',
  WALLETSETING: 'WalletSetting',
  GENERALPROFILE: 'GeneralProfile',
  // Filter Screen Additon
  FILTER: 'FilterImage',
  STORYFILTER: 'StoryFilter',
  SECURITYSETTINGS: 'SecuritySettings',
  INVITEFRIEND: 'InviteFriend',
  FEEDBACK: 'FeedBack',
  DELETEACCOUNT: 'DeleteAccount',
  CLASSIFIEDWELCOME: 'ClassifiedWelcome',
  CLASSIFIEDDISCLAIMER: 'ClassifiedDisclaimer',
  GALLERYPICKER: 'GalleryPicker',
  SUGGESTION: 'Suggestion',
  SOCIALPOSTPICKER: 'SocialPostPicker',
  SOCIALIMAGECROP: 'SocialImageCrop',
  CAREEREDITPROFILE: 'CareerEditProfile',
  CAREEREDITPROFILE1ST: 'CareerEditProfile1st',
  CAREERCREATEPROFILE:'CareerCreateProfile',
  CAREERCHOOSEOPTIONS:'CareerChooseOptions',
  CONNECTEDITPROFILE1ST: 'ConnectEditProfile1st',
  CONNECTEDITPROFILE2ND: 'ConnectEditProfile2nd',
  CONNECTEDITPROFILE3RD: 'ConnectEditProfile3rd',
  CONNECTEDITPROFILE4TH: 'ConnectEditProfile4th',
  EDUCATIONTEACHERMAKECLASS: 'EducationTeacherMakeClass',
  EDUCATIONTEACHEREDITCLASSDETAIL: 'EducationTeacherEditClassDetail',
  POSTFILTER: 'PostFilterScreen',
  WALLETPINRESET: 'WalletPinReset',
  APPINTRO: 'AppIntro',
  GENERATEQR: 'GenerateQR',
  SOCIALPOSTEDIT: 'SocialPostEdit',
  SCANWALLETQR: 'ScanWalletQr',
  GENERATEWALLETQR: 'GenerateWalletQR',
  EDUCATIONTAKECLASS: 'EducationTakeClass',
  // Mental Health
  MENTAL: 'MentalHealth',
  MENTALHOME: 'MentalHome',
  MENTALGIF: 'MentalGif',
  MENTALMOOD: 'MentalMood',
  MENTALWELCOME: 'MentalWelcome',
  MENTALSETTINGS: 'MentalSettings',
  MENTALPOSTCREATE: 'MentalPostCreate',
  MENTALPOSTDETAIL: 'MentalPostDetail',
  MENTALPOSTSAVE: 'MentalPostSave',
  MENTALPROFILE: 'MentalProfile',
  MENTALDIARY: 'MentalDiary',
  MENTALDIARYCREATE: 'MentalDiaryCreate',
  MENTALDIARYCAMERA: 'MentalDiaryCamera',
  MENTALDIARYGALLERY: 'MentalDiaryGallery',
  MENTALEXERCISE: 'Exercise',
  MENTALDIARYENTRY: 'MentalDiaryEntry',
  MENTALEXERCISEDAYS: 'ExerciseDays',
  MENTALEXERCISEDAYSCHALLENGE: 'MentalExerciseDaysChallenge',
  MENTALEXERCISEDAYSSKIP: 'MentalExerciseDaysSkip',
  MENTALEXERCISEDAYCHALLENGESTART: 'MentalExerciseDayChallengeStart',
  MENTALEXERCISETIMERRESET: 'MentalExerciseTimerReset',
  MENTALEXERCISESTATS: 'MentalExerciseStats',
  MENTALSELFLOVE: 'MentalSelfLove',
  MENTALDAYS: 'MentalDays',
  MENTALSPLASH: 'MentalSplash',
  MENTALTODO: 'MentalToDo',
  MENTALDAILYFILTER: 'MentalDailyFilter',
  MENTALGOALSHOME: 'MentalGoalsHome',
  MENTALCREATEGOAL: 'MentalCreateGoal',
  MENTALMOODTRACKER: 'MentalMoodTracker',
  MENTALMYPROGRESS: 'MentalMyProgress',
  MENTALBREATHEHOME: 'MentalBreatheHome',
  MENTALEQUALBREATHING: 'MentalEqualBreathing',
  MENTALBOXBREATHING: 'MentalBoxBreathing',
  MENTAL478BREATHING: 'Mental478Breathing',

  // Pager
  PAGER: 'Pager',
  PAGERHOME: 'PagerHome',
  PAGERGIF: 'PagerGif',
  PAGERCAMERA: 'PagerCamera',
  PAGERPOST: 'PagerPost',
  PAGERPOST1: 'PagerPost1',
  PAGERSEARCH: 'PagerSearch',
  PAGEREXPLORE: 'PagerExplore',
  PAGERFILTER: 'PagerFilter',
  PAGERPROFILE: 'PagerProfile',
  PAGERSINGLEPOST: 'PagerSinglePost',
  PAGERSAVEDPOST: 'PagerSavedPost',
  PAGERBLOCK: 'PagerBlock',
  PAGERFOLLOWER: 'PagerFollower',
  PAGERFOLLOWING: 'PagerFollowing',
  PAGERREQUEST: 'PagerRequests',
  PAGERPOSTEDIT: 'PagerPostEdit',
  PAGERSETTINGS: 'PagerSettings',
  PAGERFAVORITES: 'PagerFavorites',
  PAGERQUOTE: 'PagerQuote',

  // Book Keeping
  BOOKKEEPING: 'BookKeeping',
  BOOKKEEPINGHOME: 'BookKeepingHome',
  BOOKKEEPINGCREATEEXPENSE: 'BookKeepingCreateExpense',
  BOOKKEEPINGCREATEGOAL: 'BookKeepingCreateGoal',
  BOOKKEEPINGSTATS: 'BookKeeingStats',
  BOOKKEEPINGEDITEXPENSE: 'BookKeeingEditExpense',
  BOOKKEEPINGEDITGOAL: 'BookKeepingEditGoal',
  BOOKKEEPINGADDBALANCE: 'BookKeepingAddBalance',
  BOOKKEEPINGVIEWEXPENSE: 'BookKeeingViewExpense',
  BOOKKEEPINGVIEWGOAL: 'BookKeeingViewGoal',

  WALLETHOME: 'WalletHome',
  WALLETGIF: 'WalletGif',
  WALLETSPLASH: 'WalletSplash',
};
const TOKEN = 'token';
const MULTIPART = 'multipart';
const TOKEN_ONLY = 'tokenOnly';
const EMPTY = '';
const PUBLISHABLE_KEY =
  // 'pk_test_51LEgohISa2VwhQTgrHCCPBvtOP6ZeGKQBFFSsbOhgldS5oeo9D5ju3W3ErCEZzZsylxsdHDywIAmSGoq4IaSjpvf00pCudEJeB';
  'pk_live_51LEgohISa2VwhQTg4K69rQnoXcgcPAkBRncHKloN9TZVd9mE6aYL90MW0TNeUqwJmQQ79t3RS3BLrwcRzEchOBVt0014Fx7ovD';
export {
  screen,
  route,
  TOKEN,
  EMPTY,
  MULTIPART,
  TOKEN_ONLY,
  SCREEN_HEIGHT,
  SCREEN_WIDTH,
  Fonts,
  PUBLISHABLE_KEY,
};
