import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_HEIGHT} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerBtn: {
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: themeStyle.BAR_COLOR,
    paddingHorizontal: 15,
    paddingVertical: 5,
  },
  btnText: {
    color: themeStyle.COLOR_WHITE,
    fontSize: 12,
    marginLeft: 10,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  container: {
    flex: 1,
  },
  heading: {
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 22,
  },
  btnContainer: {
    justifyContent: 'center',
    paddingHorizontal: '5%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    marginBottom: SCREEN_HEIGHT * 0.13,
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desc: {
    marginTop: '5%',
    marginHorizontal: '5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  inputConttainer: {
    marginTop: '2.5%',
    height: 60,
    borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  grayText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    marginTop: '5%',
  },
  grayText1: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  rowContainer: {
    marginTop: '2.5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  box: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 19,
    borderColor: 'white',
    borderWidth: 2,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
    backgroundColor: themeStyle.COLOR_LIGHT_GREY,
  },
  rowContainer1: {
    marginTop: '5%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '32%',
  },
  row2: {flexDirection: 'row', justifyContent: 'space-between'},
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'gray',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'white',
  },
  dropDownContainerStyle: {
    backgroundColor: 'white',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 100,
    height: 40,
  },

  option: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    // fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  desc1: {
    // marginHorizontal: '2.5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  inputConttainer1: {
    marginTop: '2.5%',
    height: 60,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 10,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderWidth: 2,
  },
  margin: {
    // marginVertical: 10
  },
  btnSelect: {
    height: 40,
    borderRadius: 5,
    backgroundColor: themeStyle.CARRER_SECONDARY,
    marginTop: '1%',
  },
  btnDisable: {
    height: 40,
    borderRadius: 5,
    backgroundColor: themeStyle.CARRER_DISABLE_BUTTON,
    marginTop: '1%',
  },
  btnPrimaryText: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 12,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  option1: {
    marginLeft: 5,
    fontSize: 14,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedbox1: {
    //  marginHorizontal
    height: 19,
    width: 19,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderWidth: 2,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.CLASSIFIED_HOME,
  },
  selectedOption1: {
    marginLeft: 5,
    fontSize: 14,
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  box1: {
    height: 19,
    width: 19,
    borderRadius: 3,
    borderWidth: 2,
    borderColor: themeStyle.CARRER_PRIMARY,
    backgroundColor: 'white',
  },
  professionDetail: {
    fontSize: 14,
    color: '#454545',
    marginVertical: 2,
  },
  feeContainer: {
    height: null,
    marginBottom: 0,
    paddingHorizontal: 0,
    marginTop: 10,
    borderColor: themeStyle.COLOR_WHITE,
  },
  inputStylePrice: {
    fontSize: 14,
    marginLeft: '2.5%',
    fontFamily: themeStyle.FONT_REGULAR,
  },
  inputContainerStylePrice: {
    borderWidth: 2,
    borderBottomWidth: 2,
    borderColor: themeStyle.CARRER_PRIMARY,
    backgroundColor: 'transparent',
    borderRadius: 10,
    margin: 0,
    paddingLeft: 0,
    height: 60,
  },
  symbol: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 22,
  },
  marginTop: {
    marginTop: 24,
  },
  deadline: {
    borderRadius: 10,
    borderColor: themeStyle.CARRER_PRIMARY,
    borderWidth: 2,
    height: 60,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    width: '100%',
    marginBottom: 80,
  },
  deadlineText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 14,
  },
  createButton: {
    height: 60,
    borderRadius: 10,
    backgroundColor: themeStyle.CARRER_SECONDARY,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  createButtonText: {
    fontSize: 20,
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_BLACK,
  },
});
