import {StyleSheet} from 'react-native';
import themeStyle from '../../../../assets/styles/theme.style';
import {SCREEN_WIDTH} from '../../../../lib/utils/constants';

export default StyleSheet.create({
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  headerTextStyle: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
  },
  datingStyle: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    marginLeft: '5%',
    justifyContent: 'center',
    borderRadius: 15,
    borderColor: themeStyle.COLOR_WHITE,
    borderWidth: 1,
  },
  imageButton: {
    height: 70,
    width: 90,
    backgroundColor: themeStyle.COLOR_SILVER,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themeStyle.EDUCATION_BROWN,
    marginRight: 15,
  },
  headingStyle: {
    color: 'white',
    fontSize: 12,
  },
  container: {
    flex: 1,
  },
  heading: {
    color: '#99CC66',
    fontFamily: themeStyle.FONT_MEDIUM,
    fontSize: 22,
  },
  btnContainer: {
    marginHorizontal: '10%',
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  desc: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  inputConttainer: {
    marginTop: 8,
    borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  image: {height: 70, width: 90, borderRadius: 8, resizeMode: 'cover'},
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '100%',
  },
  grayText: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  rowContainer: {
    marginTop: '2.5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  enterOptionContainer: {
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    height: 140,
    paddingHorizontal: 20,
    borderRadius: 7,
    marginTop: 10,
    width: '100%',
  },
  optionInput: {
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    height: 50,
    textAlignVertical: 'top',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 7,
    color: themeStyle.COLOR_BLACK,
    borderTopWidth: 0.4,
  },
  enterOptionInput: {
    textAlignVertical: 'top',
    color: themeStyle.COLOR_BLACK,
    width: '92%',
  },
  box: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 19,
    borderColor: 'white',
    // borderWidth: 2,
    // overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.EDUCATION_BROWN,
  },
  rowContainer1: {
    flexDirection: 'row',
    marginTop: '2.5%',
  },
  row: {
    flex: 0.37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'gray',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'lightgray',
  },
  dropDownContainerStyle: {
    backgroundColor: 'lightgray',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 100,
    height: 40,
  },

  option: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.COLOR_BLACK_LIGHT,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.COLOR_BLACK_LIGHT,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    // fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  btnContainer: {
    flex: 0.13,
    justifyContent: 'space-between',
    paddingHorizontal: '5%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cancelBtn: {
    width: '49%',
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: themeStyle.COLOR_WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
  },
  postBtn: {
    width: '49%',
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: themeStyle.EDUCATION_BROWN,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
  },
  btnText: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  containerStyle: {
    marginBottom: 0,
    // width:SCREEN_WIDTH*0.9
  },
  inputContainerStyle: {
    borderWidth: 2,
    borderBottomWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    height: 150,
    width: SCREEN_WIDTH * 0.9,
    alignSelf: 'center',
  },
  inputStyle: {
    fontSize: 16,
    height: '100%',
    fontFamily: themeStyle.FONT_REGULAR,
    marginHorizontal: '2.5%',
  },
  discussion: {
    fontSize: 16,
    fontFamily: themeStyle.FONT_MEDIUM,
    color: themeStyle.COLOR_BLACK,
  },
  cancelBtn: {
    width: '49%',
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: themeStyle.COLOR_WHITE,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
  },
  postBtn: {
    width: '49%',
    borderWidth: 2,
    borderColor: themeStyle.EDUCATION_BROWN,
    backgroundColor: themeStyle.EDUCATION_BROWN,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    borderRadius: 10,
  },
  btnText: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 16,
    fontFamily: themeStyle.FONT_REGULAR,
  },
});
