import {StyleSheet} from 'react-native';
import themeStyle from '../../assets/styles/theme.style';
import {SCREEN_WIDTH, SCREEN_HEIGHT} from '../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  descStyle: {
    fontSize: 10,
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
    marginTop: '1%',
    width: '98%',
    textAlign: 'justify',
    alignSelf: 'center',
  },
  searchText: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
    width: SCREEN_WIDTH * 0.85,
    alignSelf: 'center',
    marginBottom: 13,
  },
  dotStyle: {
    width: 50,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  inactiveDotStyle: {
    width: 20,
    height: 5,
    borderRadius: 5,
    marginHorizontal: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
  },
  contentContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: SCREEN_WIDTH,
    paddingVertical: '5%',
    paddingLeft: '4.5%',
  },
  walletContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeStyle.COLOR_WHITE,
    padding: '5%',
    marginBottom: '3%',
    marginHorizontal: '5%',
    borderRadius: 10,
  },
  walletStyle: {
    flex: 0.4,
    flexDirection: 'row',
    alignItems: 'center',
  },
  walletStyle1: {
    flex: 0.4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  searchContainer: {
    height: 60,
    borderWidth: 2,
    borderColor: themeStyle.COLOR_BLACK,
    flexDirection: 'row',
    marginHorizontal: '5%',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: '3%',
  },
  priceStyle: {
    marginLeft: 12,
    color: '#38474F',
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  lockStyle: {
    marginRight: 15,
  },
  walletText: {
    marginRight: 30,
    color: '#38474F',
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 16,
  },
  paginationContainer: {
    position: 'absolute',
    top: '70%',
    alignSelf: 'center',
  },
  modalContainer: {
    padding: '5%',
    paddingTop: '2%',
    backgroundColor: themeStyle.PRIMARY_BACKGROUND_COLOR,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    // alignSelf: 'center',
    // height: SCREEN_HEIGHT * 0.5,
    // width: SCREEN_WIDTH * 0.94,
    // backgroundColor: 'white',
    // marginTop: SCREEN_HEIGHT * 0.2,
    // borderRadius:20
    alignSelf: 'center',
    height: SCREEN_HEIGHT * 0.5,
    width: SCREEN_WIDTH * 0.9,
    backgroundColor: themeStyle.PRIMARY_BACKGROUND_COLOR,
    // marginTop: SCREEN_HEIGHT * 0.2,
    marginHorizontal: SCREEN_WIDTH * 0.1,
    borderRadius: 20,
    borderColor: themeStyle.COLOR_BLACK_LIGHT,
    borderWidth: 1,
  },
  iconStyleClose: {
    // paddingLeft: SCREEN_WIDTH * 0.85,
    paddingLeft: SCREEN_WIDTH * 0.82,
    paddingTop: 5,
  },
  pinContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: SCREEN_HEIGHT * 0.05,
    alignSelf: 'center',
  },
  pinTitle: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    marginVertical: SCREEN_HEIGHT * 0.02,
    // fontSize: 18,
    // fontWeight: 'bold',
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: themeStyle.FONT_SIZE_XLARGE,
  },
  pinBtnContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    // marginVertical:deviceHeight*0.02
  },
  pinBtnText: {
    color: themeStyle.COLOR_YELLOW,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  imageStyle1: {
    height: SCREEN_HEIGHT * 0.15,
    width: SCREEN_WIDTH * 0.95,
  },
  whiteText: {
    marginLeft: 5,
    fontSize: 10,
    color: 'white',
  },
  gif: {
    width: SCREEN_WIDTH * 0.87,
    height: SCREEN_HEIGHT * 0.15,
    alignSelf: 'center',
  },
  headerRightContainer: {
    flexDirection: 'row',
    marginRight: 15,
    alignItems: 'center',
  },
  socialTitle: {
    color: themeStyle.COLOR_BLACK,
    fontSize: themeStyle.FONT_SIZE_2XLARGE,
    marginHorizontal: '5%',
    fontFamily: themeStyle.FONT_BOLD,
  },
  socialTitleHeader: {
    color: themeStyle.COLOR_BLACK,
    fontSize: 19,
    marginHorizontal: '5%',
    fontFamily: themeStyle.FONT_BOLD,
  },
  colorWhite: {
    backgroundColor: themeStyle.COLOR_WHITE,
  },
  carousel: {
    marginTop: 7,
  },
  headerLeft: {marginHorizontal: 30},
  adBanner: {
    width: SCREEN_WIDTH * 0.9,
    height: SCREEN_HEIGHT * 0.15,
    alignSelf: 'center',
  },
  banner: {aspectRatio: 194 / 63, borderRadius: 10},
  closeWallet: {
    alignItems: 'center',
    height: 45,
    width: 45,
    borderRadius: 30,
    alignSelf: 'center',
    paddingTop: 8,
  },
  loc: {marginVertical: '5%', alignItems: 'center'},
  unlockWalletTextContainer: {marginVertical: '5%', alignItems: 'center'},
  cellStyle: {
    borderWidth: 2,
    borderRadius: 8,
    borderColor: themeStyle.BOOK_KEEPING_PINK,
  },
  cellStyleFocused: {
    borderColor: themeStyle.BOOK_KEEPING_PINK,
  },
  maskView: {
    width: 10,
    height: 10,
    borderRadius: 25,
    backgroundColor: themeStyle.COLOR_BLACK_LIGHT,
  },
  enterPinView: {marginTop: '5%', alignItems: 'center'},
  enterYourPin: {
    fontSize: 20,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#000',
  },
  resetYourPin: {
    fontSize: 14,
    textDecorationLine: 'underline',
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.COLOR_BLACK_LIGHT,
  },
  userModalContainer: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  userModalInnerContainer: {
    backgroundColor: 'white',
    height: SCREEN_HEIGHT * 0.6,
    borderRadius: 20,
  },
  dropDownIcon: {
    alignSelf: 'center',
    padding: 20,
    borderRadius: 20,
  },
  chatListContainer: {
    padding: 10,
    borderRadius: 10,
    marginHorizontal: '2%',
  },
  nameContainer: {marginLeft: '5%'},
  chatUserButton: {flexDirection: 'row', alignItems: 'center'},
  unlockWalletText: {
    fontSize: 32,
    fontFamily: themeStyle.FONT_REGULAR,
    color: '#004E47',
  },
});
