import { StyleSheet } from 'react-native';
import themeStyle from '../../assets/styles/theme.style';
import { SCREEN_HEIGHT, SCREEN_WIDTH } from '../../lib/utils/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white"
  },
  heading: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 22,
  },
  cardRowContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
paddingVertical:"5%",
  },
  textBtnStyle: {
    // top: 60,
    // alignSelf:"flex-end",
    width: 150,
    height: 50,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#BAD7E9"
  },
  btnContainer: {
    flex: 0.25,
    paddingHorizontal: '10%',
    backgroundColor: "white"
  },
  rowContainer2: {
    marginTop: '15%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerRightContainer: {
    marginTop: '5%',
    marginRight: 15,
    alignItems: 'center',
  },
  desc: {
    marginTop: '5%',
    marginHorizontal: '5%',
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  inputConttainer: {
    marginTop: '2.5%',
    // backgroundColor: themeStyle.COLOR_WHITE,
    // borderRadius: 10,
  },
  inputConttainer1: {
    marginTop: '2.5%',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
    justifyContent: 'space-between',
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: "2.5%",
    // width: SCREEN_WIDTH * 0.425,
    height: 50,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,
    borderWidth: 2,
    borderColor: "#e1e1e1",
    elevation: 1,
  },
  dropContainer: {
    borderWidth: 2,
    borderColor: "#e1e1e1",
    marginTop: '2.5%',
    // marginLeft: 12.5,
    height: 50,
    paddingHorizontal: '2.5%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 10,
  },
  whiteText: {
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
  },
  darkDash: {
    backgroundColor: themeStyle.PRIMARY_TINT_COLOR,
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  inputStyle: {
    fontSize: 14,
    // marginLeft: '5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  lightDash: {
    backgroundColor: 'lightgray',
    width: 100,
    height: 5,
    borderRadius: 5,
  },
  minusContainer: {
    position: 'absolute',
    zIndex: 1000,
    backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    top: 5,
    left: '70%',
  },
  textStyle:{
    color: themeStyle.COLOR_BLACK_LIGHT,
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 16,
  },
  selectedTextStyle:{
    color: themeStyle.COLOR_WHITE,
    fontFamily: themeStyle.FONT_BOLD,
    fontSize: 16,
  },
  grayText: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 18,
    marginLeft: 5,
  },
  grayText1: {
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 12,
    // marginTop: 5,
  },
  rowContainer: {
    marginTop: '2.5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textContainer: {
    backgroundColor: themeStyle.BUTTON_COLOR,
    padding: 10,
    borderRadius: 10,
  },
  box: {
    height: 19,
    width: 19,
    borderRadius: 3,
    backgroundColor: 'lightgray',
  },
  selectedbox: {
    height: 19,
    width: 19,
    borderColor: 'white',
    borderWidth: 2,
    overflow: 'hidden',
    borderRadius: 3,
    backgroundColor: themeStyle.BUTTON_COLOR,
  },
  rowContainer1: {
    flexDirection: 'row',
  },
  row: {
    flex: 0.37,
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowStyle: {
    position: 'absolute',
    right: 0,
  },
  dropDownStyle: {
    borderTopColor: 'gray',
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
    backgroundColor: 'lightgray',
  },
  dropDownContainerStyle: {
    backgroundColor: 'lightgray',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderBottomLeftRadius: 15,
  },
  dropDownContainer: {
    width: 100,
    height: 40,
  },

  option: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  selectedOption: {
    marginLeft: 10,
    fontSize: 12,
    color: themeStyle.BUTTON_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText: {
    marginVertical: '2.5%',
    // fontSize: 12,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
  },
  headingText2: {
    fontFamily: themeStyle.FONT_REGULAR,
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontSize: 20,
  },
  emptyContainer: {
    backgroundColor: themeStyle.COLOR_WHITE,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    marginHorizontal: 30,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: 'lightgray',
  },
  desc1: {
    // marginLeft: '5%',
    color: themeStyle.COLOR_BLACK,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 16,
  },
  desc2: {
    color: themeStyle.PRIMARY_TINT_COLOR,
    fontFamily: themeStyle.FONT_REGULAR,
    fontSize: 10,
  },
  modalContainer: {
    backgroundColor: themeStyle.COLOR_WHITE,
    borderRadius: 25,
    padding: '5%',
  },
  modal2Container: {
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    height: SCREEN_HEIGHT * 0.5,
  },
  selectedButtonContainer: {
    padding: '5%',
    borderWidth: 0.5,
    // backgroundColor: themeStyle.BUTTON_COLOR,
    backgroundColor: '#0B90CF' ,
    borderRadius: 10,
    marginTop: '5%',
    borderColor: '#959FAE',
  },
  textContainer: {
    // justifyContent: "flex-start",
    marginTop: '5%',
    marginBottom: '15%',
  },
  buttonContainer: {
    padding: '5%',
    borderWidth: 0.5,
    borderRadius: 10,
    marginTop: '5%',
    borderColor: '#959FAE',
  },
  margin1: {
    padding: '5%',
    borderWidth: 0.5,
    borderRadius: 10,
    marginTop: '5%',
    borderColor: '#959FAE',
  },
});
